const airports = [
  "Atlanta, [ATL], US",
  "Chicago, [ORD],, US",
  "Beijing, [PEK],, China",
  "Kingston, NM [KIN], Jamaica",
  "Manchester, Arpt [MAN], UK",
  "London, Heathrow [LHR], UK",
  "Paris, [CDG], France",
  "Frankfurt, [FRA], Germany",
  "Dallas-Fort Worth, [DFW], US",
  "New York, [JFK], US",
  "Amsterdam, [AMS], Netherlands",
  "Shanghai, [PVG], China",
  "Singapore, [SIN], Singapore",
  "Barcelona, [BCN], Spain",
  "Seoul, [ICN], South Korea",
  "Denver, [DEN], US",
  "Miami, [MIA], US",
  "Munich, [MUC], Germany",
  "Istanbul, [IST], Turkey",
  "Hong Kong, [HKG], Hong Kong",
  "Dubai, [DXB], UAE",
  "London, [LGW], UK",
  "Guangzhou, [CAN], China",
  "Rome, [FCO], Italy",
  "Madrid, [MAD], Spain",
  "Bangkok, [BKK], Thailand",
  "Moscow, [DME], Russia",
  "Chengdu, [CTU],",
  "Toronto, [YYZ], Canada",
  "Brussels, [BRU], Belgium",
  "Vienna, [VIE], Austria",
  "Charlotte, [CLT], US",
  "Philadelphia, [PHL], US",
  "Tokyo, [NRT], Japan",
  "Duesseldorf, [DUS], Germany",
  "Xi'an, [XIY], China",
  "Kunming, [KMG], China",
  "Chongqing, [CKG], China",
  "Delhi, [DEL], India",
  "Taipei, [TPE], Taiwan",
  "Kuala Lumpur, [KUL], Malaysia",
  "Phoenix, [PHX], US",
  "Hangzhou, [HGH], China",
  "Newark, [EWR], US",
  "San Francisco, [SFO], US",
  "Las Vegas, [LAS], US",
  "Zurich, [ZRH], Switzerland",
  "Houston, [IAH], US",
  "Mexico City, [MEX], Mexico",
  "Abu Dhabi, [AUH], UAE",
  "Orlando, [MCO], US",
  "Shenzhen, [SZX], China",
  "Xiamen, [XMN], China",
  "Copenhagen, [CPH], Denmark",
  "Mumbai, [BOM], India",
  "Stockholm, [ARN], Sweden",
  "Lisbon, [LIS], Portugal",
  "Detroit, [DTW], US",
  "Minneapolis, [MSP], US",
  "Boston, [BOS], US",
  "Berlin, [TXL], Germany",
  "Dublin, [DUB], Ireland",
  "Shanghai, [SHA], China",
  "Sydney, [SYD], Australia",
  "Malaga, [AGP], Spain",
  "Paris, [ORY], France",
  "Seattle, [SEA], US",
  "Moscow, [SVO], Russia",
  "Washington, [DCA], US",
  "Sao Paulo, [GRU], Brazil",
  "Washington, [IAD], US",
  "Manila, [MNL], Philippines",
  "Milano, [MXP], Italy",
  "Changcha, [CSX], China",
  "Doha, [DOH], Qatar",
  "Jeddah, [JED], Saudi Arabia",
  "Qingdao, [TAO], China",
  "Fort Lauderdale, [FLL], US",
  "Wuhan, [WUH], China",
  "Montreal, [YUL], Canada",
  "St. Petersburg, [LED], Russia",
  "Jakarta, [CGK], Indonesia",
  "Oslo, [OSL], Norway",
  "Prague, [PRG], Czech Republic",
  "Zhengzhou, [CGO], China",
  "London, [STN], UK",
  "Nanjing, [NKG], China",
  "Geneva, [GVA], Switzerland",
  "Hamburg, [HAM], Germany",
  "Helsinki, [HEL], Finland",
  "Tenerife, [TFS], Spain",
  "New York, [LGA], US",
  "Tokyo, [HND], Japan",
  "Vancouver, [YVR], Canada",
  "Alicante, [ALC], Spain",
  "Cancun, [CUN], Mexico",
  "Gran Canaria, [LPA], Spain",
  "Bogota, [BOG], Colombia",
  "Urumqi, [URC], China",
  "Osaka, [KIX], Japan",
  "Cairo, [CAI], Egypt",
  "Brisbane, [BNE], Australia",
  "Tianjin, [TSN], China",
  "Istanbul, [SAW], Turkey",
  "Baltimore, [BWI], US",
  "Dalian, [DLC], China",
  "Salt Lake City, [SLC], US",
  "Tampa, [TPA], US",
  "Riyadh, [RUH], Saudi Arabia",
  "Lyon, [LYS], France",
  "Guiyang, [KWE], China",
  "Stuttgart, [STR], Germany",
  "Shenyang, [SHE], China",
  "Chicago, [MDW], US",
  "Tel-aviv, [TLV], Israel",
  "Jinan, [TNA], China",
  "Melbourne, [MEL], Australia",
  "Nice, [NCE], France",
  "Fuzhou, [FOC], China",
  "Cologne, [CGN], Germany",
  "Marseille, [MRS], France",
  "Birmingham, Arpt [BHX], UK",
  "Harbin, [HRB], China",
  "Nairobi, [NBO], Kenya",
  "Antalya, [AYT], Turkey",
  "Casablanca, [CMN], Morocco",
  "New Orleans, [MSY], US",
  "Venice, [VCE], Italy",
  "Warsaw, [WAW], Poland",
  "Kuwait, [KWI], Kuwait",
  "San Diego, [SAN], US",
  "Edinburgh, [EDI], UK",
  "Honolulu, [HNL], US",
  "Catania, [CTA], Italy",
  "Las Palmas, [ACE], Spain",
  "Portland, [PDX], US",
  "Lima, [LIM], Peru",
  "Nanning, [NNG], China",
  "Calgary, [YYC], Canada",
  "Bucharest, [OTP], Romania",
  "Malta, [MLA], Malta",
  "Amman, [AMM], Jordan",
  "St. Louis, [STL], US",
  "Taiyuan, [TYN], China",
  "Heraklion, [HER], Greece",
  "Sanya, [SYX], China",
  "Haikou, [HAK], China",
  "London, [LTN], UK",
  "Guilin, [KWL], China",
  "Addis Ababa, [ADD], Ethiopia",
  "Auckland, [AKL], New Zealand",
  "Panama City, [PTY], Panama",
  "Madras, [MAA], India",
  "Faro, [FAO], Portugal",
  "Muscat, [MCT], Oman",
  "San Juan, [SJU], Puerto Rico",
  "Colombo, Intl [CMB], Sri Lanka",
  "Riga, [RIX], Latvia",
  "Kiev, [KBP], Ukraine",
  "Porto, [OPO], Portugal",
  "Ibiza, [IBZ], Spain",
  "Denpasar, [DPS], Indonesia",
  "Bristol, [BRS], UK",
  "Yekaterinburg, [SVX], Russia",
  "Brasilia, [BSB], Brazil",
  "Glasgow, [GLA], UK",
  "Bangalore, [BLR], India",
  "Sharjah, [SHJ], UAE",
  "Budapest, [BUD], Hungary",
  "Kolkata, [CCU], India",
  "East Midlands, [EMA], UK",
  "Fuerteventura, [FUE], Spain",
  "Larnaca, [LCA], Cyprus",
  "Basel, [BSL], Switzerland",
  "Guadalajara, [GDL], Mexico",
  "Nantes, [NTE], France",
  "Perth, [PER], Australia",
  "Caracas, [CCS], Venezuela",
  "Novosibirsk, [OVB], Russia",
  "Algier, [ALG], Algeria",
  "Bologna, [BLQ], Italy",
  "Tunis, [TUN], Tunisia",
  "Hohhot, [HET], China",
  "Hanoi, [HAN], Vietnam",
  "Thessaloniki, [SKG], Greece",
  "Nanchang, [KHN], China",
  "Moscow, [VKO], Russia",
  "Belgrade, [BEG], Serbia",
  "Fukuoka, [FUK], Japan",
  "Bahrain, [BAH], Bahrain",
  "Nagoya, [NGO], Japan",
  "Lanzhou, [LHW], China",
  "Ninbo, [NGB], China",
  "Charleroi, [CRL], Belgium",
  "Rhodos, [RHO], Greece",
  "Austin, [AUS], US",
  "Raleigh-durham, [RDU], US",
  "Newcastle, [NCL], UK",
  "Berlin, [SXF], Germany",
  "Shijiazhuang, [SJW], China",
  "Nashville, [BNA], US",
  "Dammam, [DMM], Saudi Arabia",
  "Valencia, [VLC], Spain",
  "Wenzhou, [WNZ], China",
  "Sapporo, [CTS], Japan",
  "Bergamo, [BGY], Italy",
  "Cleveland, [CLE], US",
  "Toulouse, [TLS], France",
  "Beijing, [NAY], China",
  "Leeds, [LBA], UK",
  "Tashkent, [TAS], Uzbekistan",
  "Busan, [PUS], South Korea",
  "Kansas City, [MCI], US",
  "Macau, [MFM], Macau",
  "Santiago, [SCL], Chile",
  "Naples, [NAP], Italy",
  "Hefei, [HFE], China",
  "Hannover, [HAJ], Germany",
  "Pisa, [PSA], Italy",
  "Cincinnati, [CVG], US",
  "Buenos Aires, [EZE], Argentina",
  "Houston, [HOU], US",
  "San Jose, [SJO], Costa Rica",
  "Pittsburgh, [PIT], US",
  "Dhaka, [DAC], Bangladesh",
  "Hyderabad, [HYD], India",
  "Monterrey, [MTY], Mexico",
  "Marrakech, [RAK], Morocco",
  "Luxemburg, [LUX], Luxembourg",
  "Edmonton, [YEG], Canada",
  "Indianapolis, [IND], US",
  "Phuket, [HKT], Thailand",
  "Bergen, [BGO], Norway",
  "San Antonio, [SAT], US",
  "Eindhoven, [EIN], Netherlands",
  "Nassau, [NAS], Bahamas",
  "Bangkok, [DMK], Thailand",
  "Alma-ata, [ALA], Kazakhstan",
  "Bordeaux, [BOD], France",
  "Dakar, [DKR], Senegal",
  "Beirut, [BEY], Lebanon",
  "Izmir, [ADB], Turkey",
  "Sofia, [SOF], Bulgaria",
  "Changchun, [CGQ], China",
  "Yinchuan, [INC], China",
  "Surabaya, [SUB], Indonesia",
  "Lijiang, [LJG], China",
  "Kaohsiung, [KHH], Taiwan",
  "London, [LCY], UK",
  "Mashhad, [MHD], Iran",
  "Fort Myers, [RSW], US",
  "Columbus, [CMH], US",
  "Baku, [GYD], Azerbaijan",
  "Buenos Aires, [AEP], Argentina",
  "Bilbao, [BIO], Spain",
  "Sevilla, [SVQ], Spain",
  "Palermo, [PMO], Italy",
  "Milwaukee, [MKE], US",
  "Karachi, [KHI], Pakistan",
  "Teheran, [THR], Iran",
  "Okinawa, [OKA], Japan",
  "Tehran, [IKA], Iran",
  "Dubrovnik, [DBV], Croatia",
  "San Jose, [SJC], US",
  "Milan, [LIN], Italy",
  "Beauvais, [BVA], France",
  "Zhuhai, [ZUH], China",
  "Lagos, Murtala [LOS], Nigeria",
  "Anchorage, [ANC], US",
  "Kochi, [COK], India",
  "Cheju, [CJU], South Korea",
  "Islamabad, [ISB], Pakistan",
  "Liverpool, [LPL], UK",
  "Vilnius, [VNO], Lithuania",
  "Salvador, [SSA], Brazil",
  "Dalaman, [DLM], Turkey",
  "Krakow, [KRK], Poland",
  "Campinas, [VCP], Brazil",
  "Memphis, [MEM], US",
  "Yantai, [YNT], China",
  "Oakland, [OAK], US",
  "Lahore, [LHE], Pakistan",
  "Cairns, [CNS], Australia",
  "Belo Horizonte, [CNF], Brazil",
  "Sacramento, [SMF], US",
  "Minsk 2, [MSQ], Belarus",
  "Accra, Kotoka [ACC], Ghana",
  "Gothenborg, [GOT], Sweden",
  "Stavanger, [SVG], Norway",
  "Dushanbe, [DYU], Tajikistan",
  "Florence, [FLR], Italy",
  "Ankara, [ESB], Turkey",
  "Funchal, [FNC], Portugal",
  "Kota Kinabalu, [BKI], Malaysia",
  "Tselinograd, [TSE], Kazakhstan",
  "Olbia, [OLB], Italy",
  "Windsor Locks, [BDL], US",
  "Kerkyra/corfu, [CFU], Greece",
  "Adelaide, [ADL], Australia",
  "Abidjan, [ABJ], Cote d'Ivoire",
  "Gdansk, [GDN], Poland",
  "Bremen, [BRE], Germany",
  "Rome, [CIA], Italy",
  "Bari, [BRI], Italy",
  "Xining, [XNN], China",
  "Yangon, [RGN], Burma",
  "Douala, [DLA], Cameroon",
  "Madinah, [MED], Saudi Arabia",
  "Gerona, [GRO], Spain",
  "Cebu, [CEB], Philippines",
  "Sanford, [SFB], US",
  "Split, [SPU], Croatia",
  "Halifax, [YHZ], Canada",
  "Chiang Mai, [CNX], Thailand",
  "Nuernberg, [NUE], Germany",
  "Tripoli, [TIP], Libya",
  "Wuxi, [WUX], China",
  "Billund, [BLL], Denmark",
  "Hahn, [HHN], Germany",
  "Sao Paulo, [CGH], Brazil",
  "Luanda, [LAD], Angola",
  "Dubai, [DWC], UAE",
  "Krasnoyarsk, [KJA], Russia",
  "Puerto Vallarta, [PVR], Mexico",
  "Jacksonville, [JAX], US",
  "Krasnodar, [KRR], Russia",
  "Keflavik, [KEF], Iceland",
  "Enfidha, [NBE], Tunisia",
  "Darwin, [DRW], Australia",
  "Yerevan, [EVN], Armenia",
  "Bishkek, [FRU], Kyrgyzstan",
  "Oranjestad, [AUA], Aruba",
  "Chania, [CHQ], Greece",
  "Kos, [KGS], Greece",
  "Montego Bay, [MBJ], Jamaica",
  "Ottawa, [YOW], Canada",
  "Quanzhou, [JJN], China",
  "West Palm Beach, [PBI], US",
  "Kathmandu, Arpt [KTM], Nepal",
  "Havana, [HAV], Cuba",
  "Cape Town, [CPT], South Africa",
  "Trondheim, [TRD], Norway",
  "Santa Ana, [SNA], US",
  "Porto Alegre, [POA], Brazil",
  "Curitiba, [CWB], Brazil",
  "Torino, [TRN], Italy",
  "Cagliari, [CAG], Italy",
  "Male, [MLE], Maldives",
  "Zagreb, [ZAG], Croatia",
  "Paphos, [PFO], Cyprus",
  "Kahului, [OGG], US",
  "Penang, [PEN], Malaysia",
  "Trivandrum, [TRV], India",
  "Osaka, [ITM], Japan",
  "Albuquerque, [ABQ], US",
  "Louisville, [SDF], US",
  "Nandi, [NAN], Fiji",
  "Tijuana, [TIJ], Mexico",
  "Mauritius, Plaisance, SSR [MRU]",
  "Aberdeen, [ABZ], UK",
  "Irkutsk, [IKT], Russia",
  "Oklahoma City, [OKC], US",
  "Alexandria, [HBE], Egypt",
  "Siem-reap, [REP], Cambodia",
  "Winnipeg, [YWG], Canada",
  "Khartoum, [KRT], Sudan",
  "Cotonou, [COO], Benin",
  "Taipei, [TSA], Taiwan",
  "Lille, [LIL], France",
  "Leipzig, [LEJ], Germany",
  "Hurghada, [HRG], Egypt",
  "Quito, [UIO], Ecuador",
  "Seoul, [GMP], South Korea",
  "Shiraz, [SYZ], Iran",
  "Ajaccio, [AJA], France",
  "Kigali, [KGL], Rwanda",
  "Sharm El Sheikh, [SSH], Egypt",
  "Villafranca, [VRN], Italy",
  "Jersey, [JER], Jersey",
  "Weeze, [NRN], Germany",
  "Richmond, [RIC], US",
  "Yakutsk, [YKS], Russia",
  "Treviso, [TSF], Italy",
  "Sanaa, [SAH], Yemen",
  "Dallas, [DAL], US",
  "Khabarovsk, [KHV], Russia",
  "Sandefjord, [TRF], Norway",
  "Rygge, [RYG], Norway",
  "Changzhou, [CZX], China",
  "Norfolk, [ORF], US",
  "Djerba, [DJE], Tunisia",
  "Balikpapan, [BPN], Indonesia",
  "Recife, [REC], Brazil",
  "Bastia, [BIA], France",
  "Tirana, [TIA], Albania",
  "Shantou, [SWA], China",
  "Buffalo, [BUF], US",
  "Birmingham, [BHM], US",
  "Guayaquil, [GYE], Ecuador",
  "Fortaleza, [FOR], Brazil",
  "Belfast, [BFS], UK",
  "Ahmedabad, [AMD], India",
  "Belem, [BEL], Brazil",
  "Agana, [GUM], Guam",
  "Santiago, [SCQ], Spain",
  "Menorca, [MAH], Spain",
  "Tbilisi, [TBS], Georgia",
  "Charleston, [CHS], US",
  "Omaha, [OMA], US",
  "Salzburg, [SZG], Austria",
  "Strasbourg, [SXB], France",
  "Cork, [ORK], Ireland",
  "Myrtle Beach, [MYR], US",
  "Pune, [PNQ], India",
  "Oran, [ORN], Algeria",
  "Chisinau, [KIV], Moldova",
  "Lusaka, [LUN], Zambia",
  "Dortmund, [DTM], Germany",
  "Entebbe, [EBB], Uganda",
  "Dar Es Salaam, [DAR], Tanzania",
  "Wroclaw, [WRO], Poland",
  "Khudzhand, [LBD], Tajikistan",
  "Rotterdam, [RTM], Netherlands",
  "Southampton, [SOU], UK",
  "Danang, [DAD], Vietnam",
  "Cuiaba, [CGB], Brazil",
  "Ljubljana, [LJU], Slovenia",
  "Tenerife, [TFN], Spain",
  "Mesa, [AZA], US",
  "Dayton, [DAY], US",
  "Manaus, [MAO], Brazil",
  "Wellington, [WLG], New Zealand",
  "Guwahati, [GAU], India",
  "Cardiff, [CWL], UK",
  "Bodrum, [BJV], Turkey",
  "Stockholm, [NYO], Sweden",
  "Knoxville, [TYS], US",
  "Tucson, [TUS], US",
  "St. Petersburg, [PIE], US",
  "Sendai, [SDJ], Japan",
  "Alghero, [AHO], Italy",
  "Calicut, [CCJ], India",
  "Phnom-penh, [PNH], Cambodia",
  "Rio De Janeiro, [SDU], Brazil",
  "Lhasa, [LXA], China",
  "Erbil, [EBL], Iraq",
  "Albany, [ALB], US",
  "Rochester, [ROC], US",
  "Osh, [OSS], Kyrgyzstan",
  "Abuja, [ABV], Nigeria",
  "Peshawar, [PEW], Pakistan",
  "Yuncheng, [YCU], China",
  "Baotou, [BAV], China",
  "Shannon, [SNN], Ireland",
  "Greenville, [GSP], US",
  "Yogyakarta, [JOG], Indonesia",
  "Little Rock, [LIT], US",
  "Kuala Lumpur, [SZB], Malaysia",
  "Goa, [GOI], India",
  "Taichung, [RMQ], Taiwan",
  "Yellowknife, [YZF], Canada",
  "Des Moines, [DSM], US",
  "Bethel, [BET], US",
  "Cali, [CLO], Colombia",
  "Quebec, [YQB], Canada",
  "Harare, Intl [HRE], Zimbabwe",
  "Katowice, [KTW], Poland",
  "Reno, [RNO], US",
  "Grand Rapids, [GRR], US",
  "Coolangatta, [OOL], Australia",
  "Kazan, [KZN], Russia",
  "Rostov, [ROV], Russia",
  "Port-vila, [VLI], Vanuatu",
  "Belize City, [BZE], Belize",
  "Trapani, [TPS], Italy",
  "Agadir, [AGA], Morocco",
  "Tulsa, [TUL], US",
  "Providence, [PVD], US",
  "Bamako, [BKO], Mali",
  "Stockholm, [BMA], Sweden",
  "Samara, [KUF], Russia",
  "Batam, [BTH], Indonesia",
  "Fairbanks, [FAI], US",
  "Kabul, [KBL], Afghanistan",
  "Warsaw, [WMI], Poland",
  "Tromso, [TOS], Norway",
  "Huangshan, [TXN], China",
  "Syracuse, [SYR], US",
  "Kuching, [KCH], Malaysia",
  "Sochi, [AER], Russia",
  "Vladivostok, [VVO], Russia",
  "Rio Negro, [MDE], Colombia",
  "Zadar, [ZAD], Croatia",
  "Greensboro, [GSO], US",
  "Palm Springs, [PSP], US",
  "La Paz, [LPB], Bolivia",
  "Dongsheng, [DSN], China",
  "Ontario, [ONT], US",
  "Vientiane, [VTE], Laos",
  "Lamezia, [SUF], Italy",
  "Benghazi, [BEN], Libya",
  "Exeter, [EXT], UK",
  "Nome, [OME], US",
  "Libreville, [LBV], Gabon",
  "Yichang, [YIH], China",
  "Bentonville, [XNA], US",
  "Jinghong, [JHG], China",
  "Miri, [MYY], Malaysia",
  "Santa Cruz, [VVI], Bolivia",
  "Ahwaz, [AWZ], Iran",
  "Port-au-prince, [PAP], Haiti",
  "Hermosillo, [HMO], Mexico",
  "Skopje, [SKP], Macedonia",
  "Montpellier, [MPL], France",
  "Rankin Inlet, [YRT], Canada",
  "El Paso, [ELP], US",
  "Ponta Delgada, [PDL], Portugal",
  "Memmingen, [FMM], Germany",
  "Savannah, [SAV], US",
  "White Plains, [HPN], US",
  "Ufa, [UFA], Russia",
  "Bridgetown, [BGI], Barbados",
  "Montevideo, [MVD], Uruguay",
  "Tyumen, [TJM], Russia",
  "Kotzebue, [OTZ], US",
  "Liberia, [LIR], Costa Rica",
  "Akron, [CAK], US",
  "Aden, [ADE], Yemen",
  "Ketchikan, [KTN], US",
  "Dresden, [DRS], Germany",
  "Mineralnye Vody, [MRV], Russia",
  "Kiev, [IEV], Ukraine",
  "Sept-iles, [YZV], Canada",
  "Brindisi, [BDS], Italy",
  "Freetown, [FNA], Sierra Leone",
  "Mianyang, [MIG], China",
  "Goiania, [GYN], Brazil",
  "St. John's, [YYT], Canada",
  "Jerez, [XRY], Spain",
  "Durban, [DUR], South Africa",
  "Gothenborg, [GSE], Sweden",
  "Poznan, [POZ], Poland",
  "Dayong, [DYG], China",
  "Prestwick, [PIK], UK",
  "Belfast, [BHD], UK",
  "Aktau, [SCO], Kazakhstan",
  "Bandung, [BDO], Indonesia",
  "Lihue, [LIH], US",
  "Pensacola, [PNS], US",
  "Manado, [MDC], Indonesia",
  "Florianopolis, [FLN], Brazil",
  "Pristina, [PRN], Serbia",
  "Cluj-napoca, [CLJ], Romania",
  "Aalborg, [AAL], Denmark",
  "Kona, [KOA], US",
  "Boise, [BOI], US",
  "Ulan Bator, [ULN], Mongolia",
  "Lome, [LFW], Togo",
  "Kilimanjaro, [JRO], Tanzania",
  "St.-denis, [RUN], Reunion",
  "Beihai, [BHY], China",
  "Isfahan, [IFN], Iran",
  "Xuzhou, [XUZ], China",
  "Djibouti, Ambouli [JIB], Djibouti",
  "Lexington KY, [LEX], US",
  "Manchester NH, [MHT], US",
  "Fresno, [FAT], US",
  "Juneau, [JNU], US",
  "Wichita, [ICT], US",
  "Chelyabinsk, [CEK], Russia",
  "Bratislava, [BTS], Slovakia",
  "Genoa, [GOA], Italy",
  "Calvi, [CLY], France",
  "Murcia, [MJV], Spain",
  "Harrisburg, [MDT], US",
  "Porlamar, [PMV], Venezuela",
  "Reus, [REU], Spain",
  "Zhanjiang, [ZHA], China",
  "Bournemouth, [BOH], UK",
  "Yaounde, [NSI], Cameroon",
  "Windhoek, [WDH], Namibia",
  "Kaunas, [KUN], Lithuania",
  "Ribeirao Preto, [RAO], Brazil",
  "Bandar Abbas, [BND], Iran",
  "Graz, [GRZ], Austria",
  "Santander, [SDR], Spain",
  "Tanger, [TNG], Morocco",
  "Odessa, [ODS], Ukraine",
  "Hewandorra, [UVF], Saint Lucia",
  "Nairobi, [WIL], Kenya",
  "Yangzhou, [YTY], China",
  "Yiwu, [YIW], China",
  "Linyi, [LYI], China",
  "El Aroui, [NDR], Morocco",
  "Iqaluit, [YFB], Canada",
  "Nantong, [NTG], China",
  "Guernsey, [GCI], Guernsey",
  "Conakry, [CKY], Guinea",
  "Huntsville, [HSV], US",
  "Burbank, [BUR], US",
  "Long Beach, [LGB], US",
  "Jackson, [JAN], US",
  "Hailar, [HLD], China",
  "Johor Bahru, [JHB], Malaysia",
  "Pekanbaru, [PKU], Indonesia",
  "Ko Samui, [USM], Thailand",
  "Lucknow, [LKO], India",
  "Vishakhapatnam, [VTZ], India",
  "Asuncion, [ASU], Paraguay",
  "Kalibo, [KLO], Philippines",
  "Kagoshima, [KOJ], Japan",
  "Tegucigalpa, [TGU], Honduras",
  "Almeria, [LEI], Spain",
  "Fes, [FEZ], Morocco",
  "Punta Gorda, [PGD], US",
  "Bodo, [BOO], Norway",
  "Cedar Rapids, [CID], US",
  "Jayapura, [DJJ], Indonesia",
  "Dominica, [DOM], Dominica",
  "Maputo, [MPM], Mozambique",
  "Yancheng, [YNZ], China",
  "Praia, [RAI], Santiago Island",
  "Semarang, [SRG], Indonesia",
  "Columbia, [CAE], US",
  "Madison, [MSN], US",
  "Pulau, [LGK], Malaysia",
  "Coimbatore, [CJB], India",
  "Jaipur, [JAI], India",
  "Omsk, [OMS], Russia",
  "Lvov, [LWO], Ukraine",
  "Niamey, [NIM], Niger",
  "Campo Grande, [CGR], Brazil",
  "Hiroshima, [HIJ], Japan",
  "Kanazawa, [KMQ], Japan",
  "Nagasaki, [NGS], Japan",
  "Sioux Lookout, [YXL], Canada",
  "Adana, [ADA], Turkey",
  "Brest, [BES], France",
  "Aviles, [OVD], Spain",
  "Key West, [EYW], US",
  "Islip, [ISP], US",
  "Mandalay, [MDL], Burma",
  "Kish Island, [KIH], Iran",
  "Chihuahua, [CUU], Mexico",
  "Zakynthos, [ZTH], Greece",
  "Regina, [YQR], Canada",
  "Praya, [LOP], Indonesia",
  "Malmoe, [MMX], Sweden",
  "Lianyungang, [LYG], China",
  "Jingdezhen, [JDZ], China",
  "Changzhi, [CIH], China",
  "Niigata, [KIJ], Japan",
  "Novy Urengoy, [NUX], Russia",
  "Jiuzhaigou, [JZH], China",
  "Fort Wayne, [FWA], US",
  "Chattanooga, [CHA], US",
  "Townsville, [TSV], Australia",
  "Krabi, [KBV], Thailand",
  "Chittagong, [CGP], Bangladesh",
  "Baghdogra, [IXB], India",
  "Indore, [IDR], India",
  "Vitoria, [VIX], Brazil",
  "Natal, [NAT], Brazil",
  "Constantine, [CZL], Algeria",
  "Vera Cruz, [VER], Mexico",
  "Cozumel, [CZM], Mexico",
  "Culiacan, [CUL], Mexico",
  "Podgorica, [TGD], Montenegro",
  "Monrovia, [ROB], Liberia",
  "Mangalore, [IXE], India",
  "Monastir, [MIR], Tunisia",
  "Sao Luis, [SLZ], Brazil",
  "Wabush, [YWK], Canada",
  "Thira, [JTR], Greece",
  "Dzaoudzi, [DZA], Mayotte",
  "Kelowna, [YLW], Canada",
  "Wuyishan, [WUS], China",
  "Chifeng, [CIF], China",
  "Connaught, [NOC], Ireland",
  "Moline, [MLI], US",
  "Bermuda, [BDA], Bermuda",
  "Peoria, [PIA], US",
  "Roanoke VA, [ROA], US",
  "Tallahassee, [TLH], US",
  "Spokane, [GEG], US",
  "Nagpur, [NAG], India",
  "Ashkhabad, [ASB], Turkmenistan",
  "Kaliningrad, [KGD], Russia",
  "Donetsk, [DOK], Ukraine",
  "Uberlandia, [UDI], Brazil",
  "Tabriz, [TBZ], Iran",
  "Freeport, [FPO], Bahamas",
  "Goose Bay, [YYR], Canada",
  "Mazatlan, [MZT], Mexico",
  "Merida, [MID], Mexico",
  "Saskatoon, [YXE], Canada",
  "Pula, [PUY], Croatia",
  "Norilsk, [NSK], Russia",
  "Banjarmasin, [BDJ], Indonesia",
  "Srinagar, [SXR], India",
  "Point Salines, [GND], Grenada",
  "Abha, [AHB], Saudi Arabia",
  "Managua, [MGA], Nicaragua",
  "Del Bajio, [BJX], Mexico",
  "Yanji, [YNJ], China",
  "Huangyan, [HYN], China",
  "Liuzhou, [LZH], China",
  "Nicosia, [ECN], Cyprus",
  "Southend, [SEN], UK",
  "Springfield, [SGF], US",
  "Fargo, [FAR], US",
  "Baghdad, [BGW], Iraq",
  "Santarem, [STM], Brazil",
  "Davao, [DVO], Philippines",
  "Trenton, [TTN], US",
  "Kota Bahru, [KBR], Malaysia",
  "Ambon, [AMQ], Indonesia",
  "Surgut, [SGC], Russia",
  "Nizhnevartovsk, [NJC], Russia",
  "Dnepropetrovsk, [DNK], Ukraine",
  "Maracaibo, [MAR], Venezuela",
  "Ishigaki, [ISG], Japan",
  "Quetta, [UET], Pakistan",
  "Marsh Harbor, [MHH], Bahamas",
  "Roatan, [RTB], Honduras",
  "Toronto, [YTZ], Canada",
  "Figari, [FSC], France",
  "Boa Vista, [BVC], Cape Verde",
  "Eugene, [EUG], US",
  "Colorado Springs, [COS], US",
  "Burlington, [BTV], US",
  "Palembang, [PLM], Indonesia",
  "Avarua, [RAR], Cook Islands",
  "Toluca, [TLC], Mexico",
  "Thunder Bay, [YQT], Canada",
  "Bujumbura, [BJM], Burundi",
  "Mahe, [SEZ], Seychelles",
  "Luzhou, [LZO], China",
  "Zhoushan, [HSN], China",
  "Ganzhou, [KOW], China",
  "Xiangfan, [XFN], China",
  "Tongliao, [TGO], China",
  "Alesund, [AES], Norway",
  "Allentown, [ABE], US",
  "Flint, [FNT], US",
  "Sarasota, [SRQ], US",
  "Charlottesville VA, [CHO], US",
  "Sioux Falls, [FSD], US",
  "Wilmington, [ILM], US",
  "Kashi, [KHG], China",
  "Canberra, [CBR], Australia",
  "Mount Isa, [ISA], Australia",
  "Luang Prabang, [LPQ], Laos",
  "Maceio, [MCZ], Brazil",
  "Aracaju, [AJU], Brazil",
  "Cordoba, [COR], Argentina",
  "Okayama, [OKJ], Japan",
  "Taif, [TIF], Saudi Arabia",
  "Noumea, [NOU], New Caledonia",
  "Villahermosa, [VSA], Mexico",
  "Victoria, [YYJ], Canada",
  "Timisoara, [TSR], Romania",
  "Mykonos, [JMK], Greece",
  "Rennes, [RNS], France",
  "Mombasa, [MBA], Kenya",
  "Banjul, Arpt [BJL], Gambia",
  "Fort Mcmurray, [YMM], Canada",
  "Aniak, [ANI], US",
  "Tokua, [RAB], Papua New Guinea",
  "Patina, [PAT], India",
  "Belo Horizonte, [PLU], Brazil",
  "Gassim, [ELQ], Saudi Arabia",
  "Lilongwe, [LLW], Malawi",
  "Huai An, [HIA], China",
  "Haugesund, [HAU], Norway",
  "Wanxian, [WXN], China",
  "Yulin, [UYN], China",
  "Namangan, [NMA], Uzbekistan",
  "Misratah, [MRA], Libya",
  "Mogadishu, [MGQ], Somalia",
  "Tampere, [TMP], Finland",
  "Broome, [BME], Australia",
  "Bloomington, [BMI], US",
  "Billings, [BIL], US",
  "Asheville, [AVL], US",
  "Kobe, [UKB], Japan",
  "Gainesville, [GNV], US",
  "Jammu, [IXJ], India",
  "Cartagena, [CTG], Colombia",
  "Foz Do Iguacu, [IGU], Brazil",
  "Matsuyama, [MYJ], Japan",
  "Multan, [MUX], Pakistan",
  "Varadero, [VRA], Cuba",
  "Ciudad Juarez, [CJS], Mexico",
  "Bern, [BRN], Switzerland",
  "Iasi, [IAS], Romania",
  "La Coruna, [LCG], Spain",
  "Bourgas, [BOJ], Bulgaria",
  "Zanzibar, [ZNZ], Tanzania",
  "Juba, [JUB], South Sudan",
  "Sialkot, [SKT], Pakistan",
  "Londrina, [LDB], Brazil",
  "Nausori, [SUV], Fiji",
  "Linz, [LNZ], Austria",
  "Mulhouse, [MLH], France",
  "Nouakschott, [NKC], Mauritania",
  "Fuyang, [FUG], China",
  "Manzhouli, [NZH], China",
  "Rzeszow, [RZE], Poland",
  "Kristiansand, [KRS], Norway",
  "Datong, [DAT], China",
  "Belgorod, [EGO], Russia",
  "Santo, [SON], Vanuatu",
  "Kirkwall, [KOI], UK",
  "South Bend, [SBN], US",
  "San Pedro, [SPR], Belize",
  "Mukalla, [RIY], Yemen",
  "Chiang Rai, [CEI], Thailand",
  "Paderborn, [PAD], Germany",
  "Munster, [FMO], Germany",
  "Port Blair, [IXZ], India",
  "Raipur, [RPR], India",
  "Ulan-ude, [UUD], Russia",
  "Chita, [HTA], Russia",
  "Guayana, [PZO], Venezuela",
  "Barcelona, [BLA], Venezuela",
  "Cuzco, [CUZ], Peru",
  "Medellin, [EOH], Colombia",
  "Antofagasta, [ANF], Chile",
  "Teresina, [THE], Brazil",
  "Maraba, [MAB], Brazil",
  "Joao Pessoa, [JPA], Brazil",
  "Miyazaki, [KMI], Japan",
  "Zahedan, [ZAH], Iran",
  "Tivat, [TIV], Montenegro",
  "Preveza, [PVK], Greece",
  "Limoges, [LIG], France",
  "Bergerac, [EGC], France",
  "Vigo, [VGO], Spain",
  "Rabat, [RBA], Morocco",
  "Najaf, [NJF], Iraq",
  "Gustavia, [SBH], France",
  "Inverness, [INV], UK",
  "Charleston, [CRW], US",
  "Porto Seguro, [BPS], Brazil",
  "Kupang, [KOE], Indonesia",
  "Valparaiso, [VPS], US",
  "Ranchi, [IXR], India",
  "Chimkent, [CIT], Kazakhstan",
  "Castries, [SLU], Saint Lucia",
  "Mendoza, [MDZ], Argentina",
  "Moroni, [HAH], Comoros",
  "Ndola, [NLA], Zambia",
  "Unalakleet, [UNK], US",
  "Jining, [JNG], China",
  "Hami, [HMI], China",
  "La Rochelle, [LRH], France",
  "Shizuoka, [FSZ], Japan",
  "Jiamusi, [JMU], China",
  "Korla, [KRL], China",
  "Alta, [ALF], Norway",
  "Sulaymaniyah, [ISU], Iraq",
  "Norwich, [NWI], UK",
  "Atyrau, [GUW], Kazakhstan",
  "Mudanjiang, [MDG], China",
  "Ancona, [AOI], Italy",
  "Yibin, [YBP], China",
  "Monterey, [MRY], US",
  "Portland, [PWM], US",
  "Bellingham, [BLI], US",
  "Atlantic City, [ACY], US",
  "Varanasi, [VNS], India",
  "Volgograd, [VOG], Russia",
  "Sfax, [SFA], Tunisia",
  "Valencia, [VLN], Venezuela",
  "Arequipa, [AQP], Peru",
  "Zandery, [PBM], Suriname",
  "Barranquilla, [BAQ], Colombia",
  "Puerto Montt, [PMC], Chile",
  "Maringa, [MGF], Brazil",
  "Iloilo, [ILO], Philippines",
  "Hakodate, [HKD], Japan",
  "Rasht, [RAS], Iran",
  "Holguin, [HOG], Cuba",
  "Torreon, [TRC], Mexico",
  "Morelia, [MLM], Mexico",
  "La Paz, [LAP], Mexico",
  "Trabzon, [TZX], Turkey",
  "Prince George, [YXS], Canada",
  "Mytilini, [MJT], Greece",
  "Kalamata, [KLX], Greece",
  "Carcassonne, [CCF], France",
  "Moncton, [YQM], Canada",
  "Luxor, [LXR], Egypt",
  "Oujda, [OUD], Morocco",
  "N'djamena, [NDJ], Chad",
  "Kharkov, [HRK], Ukraine",
  "Maastricht, [MST], Netherlands",
  "Scranton, [AVP], US",
  "Amarillo, [AMA], US",
  "Lubbock, [LBB], US",
  "Cochabamba, [CBB], Bolivia",
  "Iquique, [IQQ], Chile",
  "Babelthuap, [ROR], Palau",
  "Yenbo, [YNB], Saudi Arabia",
  "Quujjuaq, [YVP], Canada",
  "Nampula, [APL], Mozambique",
  "Gaberone, [GBE], Botswana",
  "Sohag, [HMB], Egypt",
  "Godthaab, [GOH], Greenland",
  "Hatay, [HTY], Turkey",
  "Ji An, [JGS], China",
  "Harstad/Narvik, [EVE], Norway",
  "Dazhou, [DAX], China",
  "Chongju, [CJJ], South Korea",
  "Doncaster, [DSA], Sheffield",
  "Upernavik, [JUV], Greenland",
  "Blackpool, [BLK], UK",
  "Arkhangelsk, [ARH], Russia",
  "Luoyang, [LYA], China",
  "Medford, [MFR], US",
  "Appleton, [ATW], US",
  "Gulfport, [GPT], US",
  "Evansville, [EVV], US",
  "Mobile, [MOB], US",
  "Farmington, [FMN], US",
  "Newport News, [PHF], US",
  "Saarbruecken, [SCN], Germany",
  "Hobart, [HBA], Australia",
  "Sibu, [SBW], Malaysia",
  "Tiruchirappalli, [TRZ], India",
  "Chandigarh, [IXC], India",
  "Amritsar, [ATQ], India",
  "Imphal, [IMF], India",
  "Syktyvkar, [SCW], Russia",
  "Porto Velho, [PVH], Brazil",
  "Ilheus, [IOS], Brazil",
  "Toyama, [TOY], Japan",
  "Kumamoto, [KMJ], Japan",
  "Oita, [OIT], Japan",
  "Annaba, [AAE], Algeria",
  "Tabuk, [TUU], Saudi Arabia",
  "Great Exuma, [GGT], Bahamas",
  "Santa Clara, [SNU], Cuba",
  "Panama, [PAC], Panama",
  "Zihuatanejo, [ZIH], Mexico",
  "Aguascalientes, [AGU], Mexico",
  "Gaziantep, [GZT], Turkey",
  "Pescara, [PSR], Italy",
  "Samos, [SMI], Greece",
  "Beziers, [BZR], France",
  "Granada, [GRX], Spain",
  "Varna, [VAR], Bulgaria",
  "Belize, [TZA], Belize",
  "Midland, [MAF], US",
  "Kodiak, [ADQ], US",
  "Liege, [LGG], Belgium",
  "Bhubaneswar, [BBI], India",
  "Mirnyj, [MJZ], Russia",
  "Noumea, [GEA], New Caledonia",
  "Acapulco, [ACA], Mexico",
  "Pemba, [POL], Mozambique",
  "Comiso, [CIY], Italy",
  "Bijie, [BFJ], China",
  "Sondrestrom, [SFJ], Greenland",
  "Visby, [VBY], Sweden",
  "Umea, [UME], Sweden",
  "Wuhai, [WUA], China",
  "Setif, [QSF], Algeria",
  "Qiqihar, [NDG], China",
  "Guangyuan, [GYS], China",
  "Nanyang, [NNY], China",
  "Changde, [CGD], China",
  "Nadym, [NYM], Russia",
  "Khanty-Mansiysk, [HMA], Russia",
  "Salekhard, [SLY], Russia",
  "Pasco, [PSC], US",
  "Aarhus, [AAR], Denmark",
  "Pierre, [PIR], US",
  "Fayetteville, [FAY], US",
  "Gheshm, [GSM], Iran",
  "Red Lake, [YRL], Canada",
  "Inuvik, [YEV], Canada",
  "Turku, [TKU], Finland",
  "Hammerfest, [HFT], Norway",
  "Newcastle, [NTL], Australia",
  "Georgetown, [GEO], Guyana",
  "Redmond-Bend, [RDM], US",
  "Westerland, [GWT], Germany",
  "Rapid City, [RAP], US",
  "Grand Junction, [GJT], US",
  "Bozeman, [BZN], US",
  "Kutaisi, [KUT], Georgia",
  "Santa Barbara, [SBA], US",
  "Solo City, [SOC], Indonesia",
  "Baton Rouge, [BTR], US",
  "Green Bay, [GRB], US",
  "Shreveport, [SHV], US",
  "Lansing, [LAN], US",
  "Bangor, [BGR], US",
  "Port Hedland, [PHE], Australia",
  "Kununurra, [KNX], Australia",
  "Launceston, [LST], Australia",
  "Sorong, [SOQ], Indonesia",
  "Ternate, [TTE], Indonesia",
  "Heho, [HEH], Burma",
  "Madurai, [IXM], India",
  "Agartala, [IXA], India",
  "Voronezh, [VOZ], Russia",
  "Astrakhan, [ASF], Russia",
  "Trinidad, [TDD], Bolivia",
  "Tarija, [TJA], Bolivia",
  "Villavicencio, [VVC], Colombia",
  "Port Hartcourt, [PHC], Nigeria",
  "Akita, [AXT], Japan",
  "Takamatsu, [TAK], Japan",
  "Miho, [YGJ], Japan",
  "Basrah, [BSR], Iraq",
  "Mont Joli, [YYY], Canada",
  "Churchill, [YYQ], Canada",
  "San Luis Potosi, [SLP], Mexico",
  "Reynosa, [REX], Mexico",
  "Innsbruck, [INN], Austria",
  "Zaragoza, [ZAZ], Spain",
  "Vaxjo, [VXO], Sweden",
  "Kristiansund, [KSU], Norway",
  "Urgench, [UGC], Uzbekistan",
  "Deer Lake, [YDF], Canada",
  "Asmara, [ASM], Eritrea",
  "Harlingen, [HRL], US",
  "Palu, [PLW], Indonesia",
  "Orenburg, [REN], Russia",
  "Samarkand, [SKD], Uzbekistan",
  "La Ceiba, [LCE], Honduras",
  "Kayseri, [ASR], Turkey",
  "Berbera, [BBO], Somalia",
  "Hargeisa, [HGA], Somalia",
  "Tete, [TET], Mozambique",
  "Beira, [BEW], Mozambique",
  "Livingstone, [LVI], Zambia",
  "Maun, [MUB], Botswana",
  "Qianjiang, [JIQ], China",
  "Uummannaq, [UMD], Greenland",
  "Panama City, [ECP], US",
  "Dangriga, [DGA], Belize",
  "Nizhnekamsk, [NBC], Russia",
  "Szczecin, [SZZ], Poland",
  "Molde, [MOL], Norway",
  "Jiayuguan, [JGN], China",
  "Qinhuangdao, [SHP], China",
  "Anqing, [AQG], China",
  "Weifang, [WEF], China",
  "Shangri-La, [DIG], China",
  "Xilinhot, [XIL], China",
  "Ulanhot, [HLH], China",
  "Vinh, [VII], Vietnam",
  "Nha Trang, [CXR], Vietnam",
  "Buonmethuot, [BMV], Vietnam",
  "Fergana, [FEG], Uzbekistan",
  "Cherepovets, [CEE], Russia",
  "Cayo Coco, [CCC], Cuba",
  "Bissau, [OXB], Guinea-Bissau",
  "Kuujjuarapik, [YGW], Canada",
  "Qaqortoq, [JJU], Greenland",
  "Eskimo Point, [YEK], Canada",
  "Jacksonville NC, [OAJ], US",
  "Karaganda, [KGF], Kazakhstan",
  "Vadso, [VDS], Norway",
  "Klagenfurt, [KLU], Austria",
  "Dunhuang, [DNH], China",
  "Santa Cruz, [SRZ], Bolivia",
  "Missoula, [MSO], US",
  "Palmas, [PMW], Brazil",
  "BRISTOL, [TRI], US",
  "MONTGOMERY, [MGM], US",
  "Dali, [DLU], China",
  "Taiz, [TAI], Yemen",
  "Taraken, [TRK], Indonesia",
  "Great Falls, [GTF], US",
  "King Salmon, [AKN], US",
  "Plattsburgh, [PBG], US",
  "Galena, [GAL], US",
  "Bush Field, [AGS], US",
  "Karratha, [KTA], Australia",
  "Mackay, [MKY], Australia",
  "Padang, [PDG], Indonesia",
  "Tawau, [TWU], Malaysia",
  "Bintulu, [BTU], Malaysia",
  "Manokwari, [MKW], Indonesia",
  "Silchar, [IXS], India",
  "Udaipur, [UDR], India",
  "Bhopal, [BHO], India",
  "Murmansk, [MMK], Russia",
  "Simferopol, [SIP], Ukraine",
  "Aktyubinsk, [AKX], Kazakhstan",
  "Iquitos, [IQT], Peru",
  "Cayenne, [CAY], French Guiana",
  "Kano, [KAN], Nigeria",
  "La Serena, [LSC], Chile",
  "Navegantes, [NVT], Brazil",
  "Imperatriz, [IMP], Brazil",
  "Rosario, [ROS], Argentina",
  "Ladag, [CGY], Philippines",
  "Asahikawa, [AKJ], Japan",
  "Salalah, [SLL], Oman",
  "Yazd, [AZD], Iran",
  "Manzanillo, [ZLO], Mexico",
  "Zacatecas, [ZCL], Mexico",
  "Tampico, [TAM], Mexico",
  "Queretaro, [QRO], Mexico",
  "Puebla, [PBC], Mexico",
  "Diyabakir, [DIY], Turkey",
  "Val D'or, [YVO], Canada",
  "Poitiers, [PIS], France",
  "Rijeka, [RJK], Croatia",
  "Comox, [YQQ], Canada",
  "Toamasina, [TMM], Madagascar",
  "Mattala, [HRI], Sri Lanka",
  "Kulyab, [TJU], Tajikistan",
  "Placencia, [PLJ], Belize",
  "Kirkenes, [KKN], Norway",
  "Groningen, [GRQ], Netherlands",
  "Nyuang U, [NYU], Burma",
  "Barrow, [BRW], US",
  "Fort Yukon, [FYU], US",
  "Bukhara, [BHK], Uzbekistan",
  "Juliaca, [JUL], Peru",
  "Punta Arenas, [PUQ], Chile",
  "Calama, [CJC], Chile",
  "Karpathos, [AOK], Greece",
  "Keffallinia, [EFL], Greece",
  "Thompson, [YTH], Canada",
  "Natashquan, [YNA], Canada",
  "Yichun, [YIC], China",
  "Lensk, [ULK], Russia",
  "Tangshan, [TVS], China",
  "Lublin, [LUZ], Poland",
  "Jixi, [JXA], China",
  "Handan, [HDG], China",
  "Alanya, [GZP], Turkey",
  "Xingyi, [ACX], China",
  "Barreiras, [BRA], Brazil",
  "Lulea, [LLA], Sweden",
  "Stebbins, [WBB], US",
  "Gallivare, [GEV], Sweden",
  "Show Low, [SOW], US",
  "Alamosa, [ALS], US",
  "Santa Rosa, [STS], US",
  "Gorgan, [GBT], Iran",
  "Navoi, [NVI], Uzbekistan",
  "Dibrugarh, [DIB], India",
  "Nanchong, [NAO], China",
  "Quzhou, [JUZ], China",
  "Jiujiang, [JIU], China",
  "Luxi, [LUM], China",
  "Qingyang, [IQN], China",
  "Mildura, [MQL], Australia",
  "Kerry, [KIR], Ireland",
  "Wewak, [WWK], Papua New Guinea",
  "Nagoya, [NKM], Japan",
  "Mcgrath, [MCG], US",
  "Lar, [LRR], Iran",
  "Dasht-e-naz, [SRY], Iran",
  "Asyut, [ATZ], Egypt",
  "Ondjiva, [VPE], Angola",
  "Waskaganish, [YKQ], Canada",
  "Caye Caulker, [CUK], Belize",
  "Newquai, [NQY], UK",
  "Marsa Alam, [RMF], Egypt",
  "Kalymnos, [JKL], Greece",
  "Muan, [MWX], South Korea",
  "Dongying, [DOY], China",
  "Sandakan, [SDK], Malaysia",
  "Page, [PGA], US",
  "Bismarck, [BIS], US",
  "Mulu, [MZV], Malaysia",
  "Kalamazoo, [AZO], US",
  "Batumi, [BUS], Georgia",
  "Elmira, [ELM], US",
  "Wilmington, [ILG], US",
  "Alexandria, [AEX], US",
  "Mcallen, [MFE], US",
  "Cheyenne, [CYS], US",
  "Santa Fe, [SAF], US",
  "Killeen, [GRK], US",
  "Monroe, [MLU], US",
  "Newburgh, [SWF], US",
  "Bakersfield, [BFL], US",
  "Nantucket, [ACK], US",
  "Lafayette, [LFT], US",
  "Hotan, [HTN], China",
  "Erfurt, [ERF], Germany",
  "Jambi, [DJB], Indonesia",
  "Pontianak, [PNK], Indonesia",
  "Marudi, [MUR], Malaysia",
  "Cambridge Bay, [YCB], Canada",
  "Udon Thani, [UTH], Thailand",
  "Hat Yai, [HDY], Thailand",
  "Leh, [IXL], India",
  "Jodhpur, [JDH], India",
  "Aizwal, [AJL], India",
  "Campbell River, [YBL], Canada",
  "Perm, [PEE], Russia",
  "Petropavlovsk, [PKC], Russia",
  "Magadan, [GDX], Russia",
  "The Valley, [AXA], Anguilla",
  "Baker Lake, [YBK], Canada",
  "Tarapoto, [TPP], Peru",
  "Pucallpa, [PCL], Peru",
  "Sucre, [SRE], Bolivia",
  "Quibdo, [UIB], Colombia",
  "Pereira, [PEI], Colombia",
  "Leticia, [LET], Colombia",
  "Baie Comeau, [YBC], Canada",
  "Neuquen, [NQN], Argentina",
  "Salta, [SLA], Argentina",
  "Bacolod, [BCD], Philippines",
  "Zamboanga, [ZAM], Philippines",
  "Taegu, [TAE], South Korea",
  "Hassi Messaoud, [HME], Algeria",
  "Tlemcen, [TLM], Algeria",
  "Memanbetsu, [MMB], Japan",
  "Chah Bahar, [ZBR], Iran",
  "Bakhtaran, [KSH], Iran",
  "Abadan, [ABD], Iran",
  "Bejaja, [BJA], Algeria",
  "Gizan, [GIZ], Saudi Arabia",
  "Herat, [HEA], Afghanistan",
  "Poza Rico, [PAZ], Mexico",
  "Oaxaca, [OAX], Mexico",
  "London, [YXU], Canada",
  "Gibraltar, [GIB], Gibraltar",
  "Elazig, [EZS], Turkey",
  "Fort Saint John, [YXJ], Canada",
  "Horta, [HOR], Portugal",
  "Norman Wells, [YVQ], Canada",
  "Reggio Calabria, [REG], Italy",
  "Leros, [LRS], Greece",
  "Kavala, [KVA], Greece",
  "Chios, [JKH], Greece",
  "Mwanza, [MWZ], Tanzania",
  "Wajir, [WJR], Kenya",
  "Shaktoolik, [SKK], US",
  "Zweibruecken, [ZQW], Germany",
  "Aksu, [AKU], China",
  "Yan'an, [ENY], China",
  "Turbat, [TUK], Pakistan",
  "Bahawalpur, [BHV], Pakistan",
  "Whale Cove, [YXN], Canada",
  "Coral Harbour, [YZS], Canada",
  "Deadhorse, [SCC], US",
  "Concepcion, [CCP], Chile",
  "Rio Gallegos, [RGL], Argentina",
  "Trelew, [REL], Argentina",
  "Ouargla, [OGX], Algeria",
  "Adrar, [AZR], Algeria",
  "Sukkur, [SKZ], Pakistan",
  "Faleolo, [APW], Samoa",
  "Santiago De Cuba, [SCU], Cuba",
  "Kosice, [KSC], Slovakia",
  "Timmins, [YTS], Canada",
  "Sudbury, [YSB], Canada",
  "Brive, [BVE], France",
  "Antsiranana, [DIE], Madagascar",
  "Sanliurfa, [GNY], Turkey",
  "Baishan, [NBS], China",
  "Bayannur, [RLK], China",
  "Belmopan, [BCV], Belize",
  "George, [GRJ], South Africa",
  "Schefferville, [YKL], Canada",
  "Tengchong, [TCZ], China",
  "Kamloops, [YKA], Canada",
  "Laage, [RLG], Germany",
  "Angmagssalik, [AGM], Greenland",
  "Khalije Fars, [PGU], Iran",
  "Sundsvall, [SDL], Sweden",
  "Koyuk, [KKA], US",
  "Hollis, [HYL], US",
  "Craig, [CGA], US",
  "Halmstad, [HAD], Sweden",
  "Narssarssuaq, [UAK], Greenland",
  "Tongren, [TEN], China",
  "Mardin, [MQM], Turkey",
  "St Mary's, [KSM], US",
  "Dandong, [DDG], China",
  "Jinzhou, [JNZ], China",
  "Nyingchi, [LZY], China",
  "Meixian, [MXZ], China",
  "Bronnoysund, [BNN], Norway",
  "Gove, [GOV], Australia",
  "Cloncurry, [CNJ], Australia",
  "Khanabad, [KSQ], Uzbekistan",
  "Sovetskiy, [OVS], Russia",
  "Yakutia, [PYJ], Russia",
  "Kushiro, [KUH], Japan",
  "Sayun Intl, [GXF], Yemen",
  "Norsup, [NUS], Vanuatu",
  "Huntington, [HTS], US",
  "Dodge City, [DDC], US",
  "Port Sudan, [PZU], Sudan",
  "Malindi, [MYD], Kenya",
  "Heringsdorf, [HDF], Germany",
  "The Pas, [YQD], Canada",
  "Igloolik, [YGT], Canada",
  "Girua, [PNP], Papua New Guinea",
  "Stornoway, [SYY], UK",
  "Sumburgh, [LSI], UK",
  "Humberside, [HUY], UK",
  "Londonderry, [LDY], UK",
  "Vaasa, [VAA], Finland",
  "Noyabrsk, [NOJ], Russia",
  "Saratov, [RTW], Russia",
  "Liberal, [LBL], US",
  "Mehamn, [MEH], Norway",
  "Tomsk, [TOF], Russia",
  "Kulusuk, [KUS], Greenland",
  "Tanna, [TAH], Vanuatu",
  "Phu Quoc, [PQC], Vietnam",
  "Dalat, [DLI], Vietnam",
  "Saginaw, [MBS], US",
  "Kalispell, [FCA], US",
  "Wassau, [CWA], US",
  "Toledo, [TOL], US",
  "Rockford, [RFD], US",
  "Traverse City, [TVC], US",
  "Ilulissat, [JAV], Greenland",
  "Daytona Beach, [DAB], US",
  "Cold Bay, [CDB], US",
  "Corpus Christi, [CRP], US",
  "New Bern, [EWN], US",
  "Durango, [DRO], US",
  "Coppermine, [YCO], Canada",
  "Melbourne, [MLB], US",
  "Niagara Falls, [IAG], US",
  "Minot, [MOT], US",
  "Grand Forks, [GFK], US",
  "Fort Smith, [FSM], US",
  "Xichang, [XIC], China",
  "Pyongyang, [FNJ], Korea",
  "Kalgoorlie, [KGI], Australia",
  "Rockhampton, [ROK], Australia",
  "Maroochydore, [MCY], Australia",
  "Kuantan, [KUA], Malaysia",
  "Alor Setar, [AOR], Malaysia",
  "Banda Aceh, [BTJ], Indonesia",
  "Bengkulu, [BKS], Indonesia",
  "Thimphu, [PBH], Bhutan",
  "Pakse, [PKZ], Laos",
  "Dehra Dun, [DED], India",
  "Baroda, [BDQ], India",
  "Aurangabad, [IXU], India",
  "Blagoveschensk, [BQS], Russia",
  "Barquisimeto, [BRM], Venezuela",
  "Bucaramanga, [BGA], Colombia",
  "Tefe, [TFF], Brazil",
  "Rio Branco, [RBR], Brazil",
  "Petrolina, [PNZ], Brazil",
  "Passo Fundo, [PFB], Brazil",
  "Joinville, [JOI], Brazil",
  "Chapeco, [XAP], Brazil",
  "Ushuaia, [USH], Argentina",
  "Tacloban, [TAC], Philippines",
  "Miyako, [MMY], Japan",
  "Aomori, [AOJ], Japan",
  "Ibaraki, [IBR], Japan",
  "Makung, [MZG], Taiwan",
  "Kinmen, [KNH], Taiwan",
  "Bushehr, [BUZ], Iran",
  "Hail, [HAS], Saudi Arabia",
  "Kandahar, [KDH], Afghanistan",
  "Dunedin, [DUD], New Zealand",
  "Tongatapu, [TBU], Tonga",
  "Los Mochis, [LMM], Mexico",
  "Durango, [DGO], Mexico",
  "Reykjavik, [RKV], Iceland",
  "Ciudad Obregon, [CEN], Mexico",
  "Whitehorse, [YXY], Canada",
  "Terrace, [YXT], Canada",
  "Van, [VAN], Turkey",
  "Erzurum, [ERZ], Turkey",
  "Williams Lake, [YWL], Canada",
  "Elat, [ETH], Israel",
  "Perugia, [PEG], Italy",
  "Marina Di Campo, [EBA], Italy",
  "Cuneo, [CUF], Italy",
  "Rouyn, [YUY], Canada",
  "Sitia, [JSH], Greece",
  "Limnos, [LXS], Greece",
  "Nea Anghialos, [VOL], Greece",
  "Tours, [TUF], France",
  "Perpignan, [PGF], France",
  "St-Etienne, [EBU], France",
  "Metz, [ETZ], France",
  "Tarbes, [LDE], France",
  "Pau, [PUF], France",
  "Melilla, [MLN], Spain",
  "Blantyre, [BLZ], Malawi",
  "Quinhagak, [KWN], US",
  "Wales, [WAA], US",
  "Elim, [ELI], US",
  "Tanana, [TAL], US",
  "Gjoa Haven, [YHK], Canada",
  "Ruby, [RBY], US",
  "Sandnessjoen, [SSJ], Norway",
  "Mosjoen, [MJF], Norway",
  "Floro, [FRO], Norway",
  "Ganja, [KVD], Azerbaijan",
  "Flin Flon, [YFO], Canada",
  "Tobruk, [TOB], Libya",
  "Mo i Rana, [MQN], Norway",
  "Big Trout Lake, [YTL], Canada",
  "Gizo, [GZO], Solomon Islands",
  "Hodeidah, [HOD], Yemen",
  "Helena, [HLN], US",
  "Bettles, [BTT], US",
  "Tachilek, [THL], Burma",
  "Arica, [ARI], Chile",
  "Quepos, [XQP], Costa Rica",
  "Sibiu, [SBZ], Romania",
  "Vilankulu, [VNX], Mozambique",
  "Daocheng, [DCY], China",
  "Nosy-be, [NOS], Madagascar",
  "Kasane, [BBK], Botswana",
  "Beloyarsky, [EYK], Russia",
  "Parauapebas, [CKS], Brazil",
  "Araguaina, [AUX], Brazil",
  "Vilhelmina, [VHM], Sweden",
  "Postville, [YSO], Canada",
  "St. Michael, [SMK], US",
  "Lycksele, [LYC], Sweden",
  "White Mountain, [WMO], US",
  "Golovin, [GLV], US",
  "Brevig Mission, [KTS], US",
  "Noorvik, [ORV], US",
  "Kramfors, [KRF], Sweden",
  "Kiana, [IAN], US",
  "Buckland, [BKC], US",
  "Ambler, [ABL], US",
  "Thorne Bay, [KTB], US",
  "Toowoomba, [TWB], Australia",
  "Huslia, [HSL], US",
  "Montreal, [YHU], Canada",
  "Russian Mission, [RSH], US",
  "Hilton Head, [HHH], US",
  "Hamilton, [YHM], Canada",
  "Branson, [BKG], US",
  "Choibalsan, [COQ], Mongolia",
  "St-Augustin, [YIF], Canada",
  "Deering, [DRG], US",
  "Puvirnituq, [YPX], Canada",
  "Savoonga, [SVA], US",
  "Point Hope, [PHO], US",
  "Gambell, [GAM], US",
  "Panzhihua, [PZI], China",
  "Yining, [YIN], China",
  "Batsfjord, [BJF], Norway",
  "Enshi, [ENH], China",
  "Gladstone, [GLT], Australia",
  "Vagar, [FAE], Faroe Islands",
  "Broken Hill, [BHQ], Australia",
  "Haiphong, [HPH], Vietnam",
  "Bugulma, [UUA], Russia",
  "Nukus, [NCU], Uzbekistan",
  "Izhevsk, [IJK], Russia",
  "Nyagan, [NYA], Russia",
  "Kingman, [IGM], US",
  "San Cristóbal, [SCY], Ecuador",
  "Santa Maria, [RIA], Brazil",
  "Macaé, [MEA], Brazil",
  "Fukushima, [FKS], Japan",
  "Kalskag, [KLG], US",
  "Nicoya, [TNO], Costa Rica",
  "San Luis Obispo, [SBP], US",
  "Grand Island, [GRI], US",
  "Albany, [ABY], US",
  "Nanyuki, [NYK], Kenya",
  "Galcaio, [GLK], Somalia",
  "Bosaso, [BSA], Somalia",
  "Fredericton, [YFC], Canada",
  "Sogndal, [SOG], Norway",
  "Kumasi, [KMS], Ghana",
  "Batna, [BLJ], Algeria",
  "Muskrat Dam, [MSA], Canada",
  "Chevery, [YHR], Canada",
  "Hopedale, [YHO], Canada",
  "Makkovik, [YMN], Canada",
  "Nain, [YDP], Canada",
  "Apartadó, [APO], Colombia",
  "Chisasibi, [YKU], Canada",
  "Bearskin Lake, [XBE], Canada",
  "Nanortalik, [JNN], Greenland",
  "Daru, [DAU], Papua New Guinea",
  "Munda, [MUA], Solomon Islands",
  "Oulu, [OUL], Finland",
  "Mariehamn, [MHQ], Finland",
  "Naryan-Mar, [NNM], Russia",
  "Ukhta, [UCT], Russia",
  "Kzyl-Orda, [KZO], Kazakhstan",
  "Berlevag, [BVG], Norway",
  "Orsta-Volda, [HOV], Norway",
  "Copiapo, [CPO], Chile",
  "Erie, [ERI], US",
  "Vineyard Haven MA, [MVY], US",
  "Ozamis, [OZC], Philippines",
  "Legazpi, [LGP], Philippines",
  "Dipolog, [DPL], Philippines",
  "Butuan, [BXU], Philippines",
  "Astypalaia, [JTY], Greece",
  "Binghamton, [BGM], US",
  "Idaho Falls, [IDA], US",
  "Hue, [HUI], Vietnam",
  "El Calafate, [FTE], Argentina",
  "Manhattan, [MHK], US",
  "Champaign, [CMI], US",
  "Rochester, [RST], US",
  "Uluru, [AYQ], Australia",
  "Caticlan, [MPH], Philippines",
  "Surat Thani, [URT], Thailand",
  "Clyde River, [YCY], Canada",
  "Ithaca, [ITH], US",
  "Lewiston, [LWS], US",
  "Labuhan Bajo, [LBJ], Indonesia",
  "Ende, [ENE], Indonesia",
  "Kendari, [KDI], Indonesia",
  "Youngstown, [YNG], US",
  "Watertown, [ART], US",
  "Columbia, [COU], US",
  "Laredo, [LRD], US",
  "Salisbury, [SBY], US",
  "Luebeck, [LBC], Germany",
  "Duluth, [DLH], US",
  "Hilo, [ITO], US",
  "Albury, [ABX], Australia",
  "Charlieville, [CTL], Australia",
  "Dili, [DIL], East Timor",
  "Labuan, [LBU], Malaysia",
  "Gorontalo, [GTO], Indonesia",
  "Timika, [TIM], Indonesia",
  "Biak, [BIK], Indonesia",
  "Myitkyina, [MYT], Burma",
  "Stavropol, [STW], Russia",
  "Makhachkala, [MCX], Russia",
  "Abakan, [ABA], Russia",
  "Bratsk, [BTK], Russia",
  "Aguadilla, [BQN], Puerto Rico",
  "St. Martin, [SFG], Guadeloupe",
  "Maturin, [MUN], Venezuela",
  "Paraguana, [LSP], Venezuela",
  "Bagotville, [YBG], Canada",
  "Yacuiba, [BYC], Bolivia",
  "Santa Marta, [SMR], Colombia",
  "Cucuta, [CUC], Colombia",
  "Puerto Asis, [PUU], Colombia",
  "Balmaceda, [BBA], Chile",
  "Uberaba, [UBA], Brazil",
  "Bahia Blanca, [BHI], Argentina",
  "Iguazu Falls, [IGR], Argentina",
  "Dumaguete, [DGT], Philippines",
  "Ghardaia, [GHA], Algeria",
  "Kwangju, [KWJ], South Korea",
  "Biskra, [BSK], Algeria",
  "Hanamaki, [HNA], Japan",
  "Kochi, [KCZ], Japan",
  "Fukue, [FUJ], Japan",
  "Hualien, [HUN], Taiwan",
  "Kiritimati, [CXI], Kiribati",
  "Abu Dhabi, [AZI], UAE",
  "Tamanrasset, [TMR], Algeria",
  "Kerman, [KER], Iran",
  "Nelson, [NSN], New Zealand",
  "Hamilton, [HLZ], New Zealand",
  "Cockburn Town, [ZSA], Bahamas",
  "Spence Bay, [YYH], Canada",
  "Mexicali, [MXL], Mexico",
  "Charlottetown, [YYG], Canada",
  "Smithers, [YYD], Canada",
  "Pangnirtung, [YXP], Canada",
  "Malatya, [MLX], Turkey",
  "Sivas, [VAS], Turkey",
  "Cranbrook, [YXC], Canada",
  "Pico, [PIX], Portugal",
  "Flores, [FLW], Portugal",
  "Ostrava, [OSR], Czech Republic",
  "Parma, [PMF], Italy",
  "Hall Beach, [YUX], Canada",
  "Repulse Bay, [YUT], Canada",
  "Kasos, [KSJ], Greece",
  "Kithira, [KIT], Greece",
  "Nimes, [FNI], France",
  "Caen, [CFR], France",
  "Fort Smith, [YSM], Canada",
  "Rodez, [RDZ], France",
  "Quesnel, [YQZ], Canada",
  "Grande Prairie, [YQU], Canada",
  "Osijek, [OSI], Croatia",
  "Lamu, [LAU], Kenya",
  "Aswan, [ASW], Egypt",
  "Nouadhibou, [NDB], Mauritania",
  "Bulawayo, [BUQ], Zimbabwe",
  "Masai Mara, [MRE], Kenya",
  "Kotlik, [KOT], US",
  "Kwigillingok, [KWK], US",
  "Emmonak, [EMK], US",
  "Bonaventure, [YVB], Canada",
  "Samburu South, [UAS], Kenya",
  "Sege, [EGM], Solomon Islands",
  "Nicoya, [TMU], Costa Rica",
  "Anaktuvuk Pass, [AKP], US",
  "Dryden, [YHD], Canada",
  "Andoya, [ANX], Norway",
  "Longreach, [LRE], Australia",
  "Haines, [HNS], US",
  "Skagway, [SGY], US",
  "Craig Cove, [CCV], Vanuatu",
  "Pikangikum, [YPM], Canada",
  "Inukjuak, [YPH], Canada",
  "Stokmarknes, [SKN], Norway",
  "Ikaria, [JIK], Greece",
  "Lanai, [LNY], US",
  "Molokai, [MKK], US",
  "Fak Fak, [FKQ], Indonesia",
  "Dzhambul, [DMB], Kazakhstan",
  "Pelotas, [PET], Brazil",
  "Altamira, [ATM], Brazil",
  "Campos, [CAW], Brazil",
  "Golfito, [GLF], Costa Rica",
  "Konya, [KYA], Turkey",
  "Tirgu Mures, [TGM], Romania",
  "Valladolid, [VLL], Spain",
  "Eldoret, [EDL], Kenya",
  "Quelimane, [UEL], Mozambique",
  "Inhambane, [INH], Mozambique",
  "Lubango, [SDD], Angola",
  "Soyo, [SZA], Angola",
  "Menongue, [SPP], Angola",
  "Huambo, [NOV], Angola",
  "Toliara, [TLE], Madagascar",
  "Sambava, [SVB], Madagascar",
  "Mahajanga, [MJN], Madagascar",
  "Antalaha, [ANM], Madagascar",
  "Sigiriya, [GIU], Sri Lanka",
  "St.-pierre, [ZSE], Reunion",
  "Moosonee, [YMO], Canada",
  "Brusselton, [BQB], Australia",
  "Yongzhou, [LLF], China",
  "Bauru, [JTC], Brazil",
  "Toksook Bay, [OOK], US",
  "Baise, [AEB], China",
  "Ukunda, [UKA], Kenya",
  "Waterloo, [YKF], Canada",
  "Provo, [PVU], US",
  "Zhijiang, [HJJ], China",
  "Liping, [HZH], China",
  "Pond Inlet, [YIO], Canada",
  "Jijiga, [JIJ], Ethiopia",
  "Joacaba, [JCB], Brazil",
  "Dourados, [DOU], Brazil",
  "Sinop, [OPS], Brazil",
  "Cabo Frio, [CFB], Brazil",
  "Vasteras, [VST], Sweden",
  "Bella Bella, [ZEL], Canada",
  "Skelleftea, [SFT], Sweden",
  "St. George, [STG], US",
  "Kiruna, [KRN], Sweden",
  "Grayling, [KGX], US",
  "Tuluksak, [TLT], US",
  "Akiak, [AKI], US",
  "Pilot Station, [PQS], US",
  "Kongiganak, [KKH], US",
  "Klawock, [KLW], US",
  "Kipnuk, [KPN], US",
  "Hay River, [YHY], Canada",
  "Teller, [TLA], US",
  "Kobuk, [OBU], US",
  "Metakatla, [MTM], US",
  "Hoonah, [HNH], US",
  "Shungnak, [SHG], US",
  "Nulato, [NUL], US",
  "Kwethluk, [KWT], US",
  "Eek, [EEK], US",
  "Shageluk, [SHX], US",
  "Kalkmar, [KLR], Sweden",
  "Alliance, [AIA], US",
  "Chadron, [CDR], US",
  "Corozal, [CZH], Belize",
  "Chefornak, [CYF], US",
  "Puntarenas, [DRK], Costa Rica",
  "Mohe County, [OHE], China",
  "Ronneby, [RNB], Sweden",
  "Marquette, [MQT], US",
  "Holman Island, [YHI], Canada",
  "Mus, [MSR], Turkey",
  "Walvis Bay, [WVB], Namibia",
  "Punta del Este, [PDP], Uruguay",
  "Chaoyang, [CHG], China",
  "Wuzhou, [WUZ], China",
  "Shishmaref, [SHH], US",
  "Kivalina, [KVL], US",
  "Kaltag, [KAL], US",
  "Anvik, [ANV], US",
  "Stord, [SRP], Norway",
  "Svalbard, [LYR], Norway",
  "Heihe, [HEK], China",
  "Bangda, [BPX], China",
  "Zhaotong, [ZAT], China",
  "Simao, [SYM], China",
  "Burnie, [BWT], Australia",
  "Roma, [RMA], Australia",
  "Paraburdoo, [PBO], Australia",
  "Moranbah, [MOV], Australia",
  "Maningrida, [MNG], Australia",
  "Merimbula, [MIM], Australia",
  "Geraldton, [GET], Australia",
  "Doomadgee, [DMD], Australia",
  "Albany, [ALH], Australia",
  "Lawas, [LWY], Malaysia",
  "Pleiku, [PXU], Vietnam",
  "Phucat, [UIH], Vietnam",
  "Can Tho, [VCA], Vietnam",
  "Gan Island, [GAN], Maldives",
  "Andizhan, [AZN], Uzbekistan",
  "Kirov, [KVX], Russia",
  "Kostanay, [KSN], Kazakhstan",
  "El Vigía, [VIG], Venezuela",
  "Esmeraldas, [ESM], Ecuador",
  "Roxas City, [RXS], Philippines",
  "Tuguegarao, [TUG], Philippines",
  "Sacheon, [HIN], South Korea",
  "Holy Cross, [HCR], US",
  "Gustavus, [GST], US",
  "Uromiyeh, [OMH], Iran",
  "Ardabil, [ADU], Iran",
  "Ipota, [IPA], Vanuatu",
  "Gaua Island, [ZGU], Vanuatu",
  "Lonorore, [LNE], Vanuatu",
  "Loh/Linua, [TOH], Vanuatu",
  "Sola, [SLH], Vanuatu",
  "Ablow, [MTV], Vanuatu",
  "Savusavu, [SVU], Fiji",
  "Matei, [TVU], Fiji",
  "Arthur's Town, [ATC], Bahamas",
  "Kahramanmaras, [KCM], Turkey",
  "Kars, [KSY], Turkey",
  "Worland, [WRL], US",
  "Valdosta, [VLD], US",
  "Rock Springs, [RKS], US",
  "Latrobe, [LBE], US",
  "Brunswick, [BQK], US",
  "Watertown, [ATY], US",
  "Al Bayda', [LAQ], Libya",
  "Essadouira, [ESU], Morocco",
  "Dakhla, [VIL], Western Sahara",
  "Windhoek, [ERS], Namibia",
  "Ängelholm, [AGH], Sweden",
  "Östersund, [OSD], Sweden",
  "Bydgoszcz, [BZG], Poland",
  "Vardø, [VAW], Norway",
  "Svolvær, [SVJ], Norway",
  "Rørvik, [RVK], Norway",
  "Namsos, [OSY], Norway",
  "Leknes, [LKN], Norway",
  "Papa Westray, [PPW], UK",
  "North Ronaldsay, [NRL], UK",
  "Sandy Lake, [ZSJ], Canada",
  "Sanikiluaq, [YSK], Canada",
  "Umiujaq, [YUD], Canada",
  "Chibougamau, [YMT], Canada",
  "Aupaluk, [YPJ], Canada",
  "Fort Hope, [YFH], Canada",
  "Kangirsuk, [YKG], Canada",
  "Sisimiut, [JHS], Greenland",
  "Qaanaaq, [NAQ], Greenland",
  "Tari, [TIZ], Papua New Guinea",
  "Moro, [MXH], Papua New Guinea",
  "Teesside, [MME], UK",
  "Pori, [POR], Finland",
  "Lappeenranta, [LPP], Finland",
  "Arcata CA, [ACV], US",
  "Uraj, [URJ], Russia",
  "Anapa, [AAQ], Russia",
  "Kruunupyy, [KOK], Finland",
  "ST MARY\\'S, [ISC], UK",
  "Gillette, [GCC], US",
  "Columbus, [CSG], US",
  "Busuanga, [USU], Philippines",
  "NAPIER, [NPE], New Zealand",
  "Nauru, [INU], Nauru",
  "La Crosse, [LSE], US",
  "Flores, [FRS], Guatemala",
  "Aasiaat, [JEG], Greenland",
  "Tagbilaran, [TAG], Philippines",
  "Palanga, [PLQ], Lithuania",
  "Bima, [BMU], Indonesia",
  "Palangkaraya, [PKY], Indonesia",
  "Malang, [MLG], Indonesia",
  "Casper, [CPR], US",
  "Unalaska, [DUT], US",
  "Sitka, [SIT], US",
  "Tyler, [TYR], US",
  "Dothan, [DHN], US",
  "Brownsville, [BRO], US",
  "College Station, [CLL], US",
  "Cincinnati, [LUK], US",
  "Kenai, [ENA], US",
  "Cordova, [CDV], US",
  "Yuma, [YUM], US",
  "Lincoln, [LNK], US",
  "Lake Charles, [LCH], US",
  "Huron, [HON], US",
  "Dillingham, [DLG], US",
  "St. Paul Island, [SNP], US",
  "Wagga Wagga, [WGA], Australia",
  "Dubbo, [DBO], Australia",
  "Learmonth, [LEA], Australia",
  "Prosserpine, [PPP], Australia",
  "Merauke, [MKQ], Indonesia",
  "Nabire, [NBX], Indonesia",
  "Sittwe, [AKY], Burma",
  "Phitsanulok, [PHS], Thailand",
  "Rajahmundry, [RJA], India",
  "Vijayawada, [VGA], India",
  "Savannakhet, [ZVK], Laos",
  "Jessore, [JSR], Bangladesh",
  "Cox's Bazar, [CXB], Bangladesh",
  "Surat, [STV], India",
  "Rajkot, [RAJ], India",
  "Jabalpur, [JLR], India",
  "Tozeur, [TOE], Tunisia",
  "Kemorovo, [KEJ], Russia",
  "Barnaul, [BAX], Russia",
  "Pavlodar, [PWQ], Kazakhstan",
  "Uralsk, [URA], Kazakhstan",
  "Puerto Maldonado, [PEM], Peru",
  "Pasto, [PSO], Colombia",
  "Mitu, [MVP], Colombia",
  "Monteria, [MTR], Colombia",
  "Ibague, [IBE], Colombia",
  "Cuenca, [CUE], Ecuador",
  "Coca, [OCC], Ecuador",
  "Temuco, [ZCO], Chile",
  "Enugu, [ENU], Nigeria",
  "Macapa, [MCP], Brazil",
  "Montes Claros, [MOC], Brazil",
  "Ipatinga, [IPN], Brazil",
  "Caxias Do Sul, [CXJ], Brazil",
  "Cascavel, [CAC], Brazil",
  "Boa Vista, [BVB], Brazil",
  "Tamale, [TML], Ghana",
  "Esquel, [EQS], Argentina",
  "St. Anthony, [YAY], Canada",
  "Cotabato, [CBO], Philippines",
  "Pohang, [KPO], South Korea",
  "Ulsan, [USN], South Korea",
  "Yeosu, [RSU], South Korea",
  "Yamagata, [GAJ], Japan",
  "Kitakyushu, [KKJ], Japan",
  "Tsushima, [TSJ], Japan",
  "Yamaguchi, [UBJ], Japan",
  "Obihiro, [OBO], Japan",
  "Pohnpei, [PNI], Micronesia",
  "Gwadar, [GWD], Pakistan",
  "Nejran, [EAM], Saudi Arabia",
  "Bisha, [BHH], Saudi Arabia",
  "El-baha, [ABT], Saudi Arabia",
  "Al-ahsa, [HOF], Saudi Arabia",
  "Woodbourne, [BHE], New Zealand",
  "Tauranga, [TRG], New Zealand",
  "Rotorua, [ROT], New Zealand",
  "Lifou, [LIF], New Caledonia",
  "Tarawa, [TRW], Kiribati",
  "Camaguey, [CMW], Cuba",
  "Cap Haitien, [CAP], Haiti",
  "Palmar Sur, [PMZ], Costa Rica",
  "Colima, [CLQ], Mexico",
  "Tepic, [TPQ], Mexico",
  "Fort Nelson, [YYE], Canada",
  "Huatulco, [HUX], Mexico",
  "Batman, [BAL], Turkey",
  "Erzincan, [ERC], Turkey",
  "Porto Santo, [PXO], Portugal",
  "Tel-aviv, [SDV], Israel",
  "Rimini, [RMI], Italy",
  "Pantelleria, [PNL], Italy",
  "Lampedusa, [LMP], Italy",
  "Skiros, [SKU], Greece",
  "Patras, [GPA], Greece",
  "Alexandroupolis, [AXD], Greece",
  "Hyeres, [TLN], France",
  "Dinard, [DNR], France",
  "Cape Dorset, [YTE], Canada",
  "St. John, [YSJ], Canada",
  "Dole, [DLE], France",
  "Castres, [DCM], France",
  "Gander, [YQX], Canada",
  "San Sebastian, [EAS], Spain",
  "Kufra, [AKF], Libya",
  "Kenora, [YQK], Canada",
  "Windsor, [YQG], Canada",
  "Makale, [MQX], Ethiopia",
  "Lalibella, [LLI], Ethiopia",
  "Dire Dawa, [DIR], Ethiopia",
  "Hierro, [VDE], Spain",
  "Goma, [GOM], Congo (Kinshasa)",
  "Cabinda, [CAB], Angola",
  "Tununak, [TNK], US",
  "Nightmute, [NME], US",
  "Ravensthorpe, [RVT], Australia",
  "Allakaket, [AET], US",
  "Noatak, [WTK], US",
  "Erechim, [ERM], Brazil",
  "Seattle, [LKE], US",
  "Esperance, [EPR], Australia",
  "Saga, [HSG], Japan",
  "Ambryn Island, [ULB], Vanuatu",
  "Ahe, [AHE], French Polynesia",
  "New Bedford, [EWB], US",
  "Clarksburg, [CKB], US",
  "Sorkjosen, [SOJ], Norway",
  "Sanday, [NDY], UK",
  "Round Lake, [ZRJ], Canada",
  "Fort Severn, [YER], Canada",
  "Fort Frances, [YAG], Canada",
  "Wunnumin Lake, [WNN], Canada",
  "Angling Lake, [YAX], Canada",
  "Punta Gorda, [PND], Belize",
  "Narsaq, [JNS], Greenland",
  "Forde, [FDE], Norway",
  "Springfield, [SPI], US",
  "Honningsvag, [HVG], Norway",
  "Kemi, [KEM], Finland",
  "Jyvaskyla, [JYV], Finland",
  "Barnstable, [HYA], US",
  "Maumere, [MOF], Indonesia",
  "El Dorado, [ELD], US",
  "Kaimana, [KNG], Indonesia",
  "Cobija, [CIJ], Bolivia",
  "In Salah, [INZ], Algeria",
  "Aitutaki, [AIT], Cook Islands",
  "Bocas Del Toro, [BOC], Panama",
  "Kisumu, [KIS], Kenya",
  "High Level, [YOJ], Canada",
  "Lichinga, [VXC], Mozambique",
  "Saurimo, [VHC], Angola",
  "Malanje, [MEG], Angola",
  "Kuito, [SVP], Angola",
  "Tolagnaro, [FTU], Madagascar",
  "Xiahe city, [GXH], China",
  "Bingol, [BGG], Turkey",
  "Morondava, [MOQ], Madagascar",
  "Igdir, [IGD], Turkey",
  "Garoua, [GOU], Cameroon",
  "Bodaibo, [ODO], Russia",
  "Bata, [BSG], Equatorial Guinea",
  "Kooddoo, [GKK], Maldives",
  "Lankaran, [LLK], Azerbaijan",
  "Francistown, [FRW], Botswana",
  "Upington, [UTN], South Africa",
  "Al-Ula, [ULH], Saudi Arabia",
  "Cacador, [CFC], Brazil",
  "Arctic Bay, [YAB], Canada",
  "Kegaska, [ZKG], Canada",
  "Newtok, [WWT], US",
  "Juiz de Fora, [IZA], Brazil",
  "Friday Harbor, [FBS], US",
  "Westsound, [WSX], US",
  "Roche Harbor, [RCE], US",
  "Kimberley, [KIM], South Africa",
  "NAYPYITAW, [NYT], Burma",
  "Zhongwei, [ZHY], China",
  "Shiquanhe, [NGQ], China",
  "Yushu, [YUS], China",
  "Sevastopol, [UKS], Ukraine",
  "Zonguldak, [ONQ], Turkey",
  "Latacunga, [LTX], Ecuador",
  "Morristown, [MMU], US",
  "Rundu, [NDU], Namibia",
  "Ulawa, [RNA], Solomon Islands",
  "Itaituba, [ITB], Brazil",
  "Wenshan, [WNH], China",
  "Lincang, [LNJ], China",
  "Baoshan, [BSD], China",
  "Okha, [OHH], Russia",
  "Foshan, [FUO], China",
  "Norrkoeping, [NRK], Sweden",
  "Linkoeping, [LPI], Sweden",
  "Borlange, [BLE], Sweden",
  "La Chorrera, [LCR], Colombia",
  "Saravena, [RVE], Colombia",
  "Rerrenabaque, [RBQ], Bolivia",
  "Orebro, [ORB], Sweden",
  "Arvidsjaur, [AJR], Sweden",
  "Rainbow Lake, [YOP], Canada",
  "Kangiqsujuaq, [YWB], Canada",
  "Sleetmute, [SLQ], US",
  "Wainwright, [AIN], US",
  "Nunapitchuk, [NUP], US",
  "Koyukuk, [KYU], US",
  "Nunam Iqua, [SXP], US",
  "Alakanuk, [AUK], US",
  "Selawik, [WLK], US",
  "Ouzinkie, [KOZ], US",
  "Sveg, [EVG], Sweden",
  "Beaver, [WBQ], US",
  "Venetie, [VEE], US",
  "Hughes, [HUS], US",
  "Chalkyitsik, [CIK], US",
  "Tuntutuliak, [WTL], US",
  "Marshall, [MLL], US",
  "Kasigluk, [KUK], US",
  "Nuiqsut, [NUI], US",
  "Mammoth Lakes, [MMH], US",
  "Dickinson, [DIK], US",
  "Jamestown, [JHW], US",
  "Ulyanovsk, [ULV], Russia",
  "Aspen, [ASE], US",
  "Mora, [MXX], Sweden",
  "Osubi, [QRW], Nigeria",
  "Greenville, [PGV], US",
  "Lewisburg, [LWB], US",
  "Brainerd, [BRD], US",
  "Altay, [AAT], China",
  "Ust-Kut, [UKX], Russia",
  "Joenkoeping, [JKG], Sweden",
  "Iron Mountain, [IMT], US",
  "Yakutat, [YAK], US",
  "Taree, [TRO], Australia",
  "Mpacha, [MPA], Namibia",
  "Long Akah, [LKH], Malaysia",
  "Geneina, [EGN], Sudan",
  "Kangra, [DHM], India",
  "Tacheng, [TCG], China",
  "Sand Point, [SDP], US",
  "Gorakhpur, [GOP], India",
  "Araracuara, [ACR], Colombia",
  "Hagerstown, [HGR], US",
  "Pajala, [PJA], Sweden",
  "Imo, [QOW], Nigeria",
  "Tasiujaq, [YTQ], Canada",
  "Hooper Bay, [HPB], US",
  "Atqasuk, [ATK], US",
  "Lakselv, [LKL], Norway",
  "Hasvik, [HAA], Norway",
  "Worcester, [ORH], US",
  "Karamay, [KRY], China",
  "Kuqa, [KCA], China",
  "Muren, [MXV], Mongolia",
  "Bayankhongor, [BYN], Mongolia",
  "Golmud, [GOQ], China",
  "Winton, [WIN], Australia",
  "Windorah, [WNR], Australia",
  "St George, [SGO], Australia",
  "Quilpie, [ULP], Australia",
  "Pormpuraaw, [EDR], Australia",
  "Port Lincoln, [PLO], Australia",
  "Parkes, [PKE], Australia",
  "Newman, [ZNE], Australia",
  "Normanton, [NTN], Australia",
  "Narrandera, [NRA], Australia",
  "Moruya, [MYA], Australia",
  "Gaspe, [YGP], Canada",
  "Kowanyama, [KWM], Australia",
  "King Island, [KNS], Australia",
  "Julia Creek, [JCK], Australia",
  "Griffith, [GFF], Australia",
  "Cunnamulla, [CMA], Australia",
  "Bathurst, [BHS], Australia",
  "Boulia, [BQL], Australia",
  "Burketown, [BUC], Australia",
  "Bedourie, [BEU], Australia",
  "Birdsville, [BVI], Australia",
  "Aurukun, [AUU], Australia",
  "Laut Island, [KBU], Indonesia",
  "Kudat, [KUD], Malaysia",
  "Bario, [BBN], Malaysia",
  "Mukah, [MKM], Malaysia",
  "Long Seridan, [ODN], Malaysia",
  "Long Datih, [LGL], Malaysia",
  "Dawei, [TVY], Burma",
  "Conson, [VCS], Vietnam",
  "Laamu Atoll, [KDO], Maldives",
  "Dimapur, [DMU], India",
  "Koggala, [KCT], Sri Lanka",
  "Hubli, [HBX], India",
  "Saransk, [SKX], Russia",
  "Cheboksary, [CSY], Russia",
  "Vorkuta, [VKT], Russia",
  "Termez, [TMJ], Uzbekistan",
  "Kurgan, [KRO], Russia",
  "Novokuznetsk, [NOZ], Russia",
  "Zaporozhye, [OZH], Ukraine",
  "Esbjerg, [EBJ], Denmark",
  "Anadyr, [DYR], Russia",
  "Tiksi, [IKS], Russia",
  "Cherskiy, [CYX], Russia",
  "Chokurdah, [CKH], Russia",
  "Zhezkazgan, [DZN], Kazakhstan",
  "Kokshetau, [KOV], Kazakhstan",
  "Ji-Paraná, [JPR], Brazil",
  "Huánuco, [HUU], Peru",
  "Cajamarca, [CJA], Peru",
  "Yopal, [EYP], Colombia",
  "Waterford, [WAT], Ireland",
  "Marília, [MII], Brazil",
  "Catarman, [CRM], Philippines",
  "Basco, [BSO], Philippines",
  "Naga, [WNP], Philippines",
  "Kunsan, [KUV], South Korea",
  "Fort Simpson, [YFS], Canada",
  "Wrangell, [WRG], US",
  "Chevak, [VAK], US",
  "Mountain Village, [MOU], US",
  "Chitral, [CJL], Pakistan",
  "Al Ain, [AAN], UAE",
  "Noshahr, [NSH], Iran",
  "Al-Jawf, [AJF], Saudi Arabia",
  "Dawadmi, [DWD], Saudi Arabia",
  "Tiga, [TGJ], New Caledonia",
  "Futuna Island, [FTA], Vanuatu",
  "Dillon's Bay, [DLY], Vanuatu",
  "Aniwa, [AWD], Vanuatu",
  "Lamen Bay, [LNB], Vanuatu",
  "Lamap, [LPM], Vanuatu",
  "Paama Island, [PBJ], Vanuatu",
  "Longana, [LOD], Vanuatu",
  "Lambasa, [LBS], Fiji",
  "Vunisea, [KDV], Fiji",
  "Colonel Hill, [CRI], Bahamas",
  "Jalapa, [JAL], Mexico",
  "Adiyaman, [ADF], Turkey",
  "Agri, [AJI], Turkey",
  "Corvo, [CVU], Portugal",
  "Syros Island, [JSY], Greece",
  "Tupelo, [TUP], US",
  "Santa Maria, [SMX], US",
  "Rhinelander, [RHI], US",
  "Owensboro, [OWB], US",
  "North Bend, [OTH], US",
  "Lynchburg, [LYH], US",
  "Klamath Falls, [LMT], US",
  "Lebanon, [LEB], US",
  "Hot Springs, [HOT], US",
  "Du Bois, [DUJ], US",
  "Crescent City, [CEC], US",
  "Burlington, [BRL], US",
  "Bradford, [BFD], US",
  "Alpena, [APN], US",
  "Waterloo, [ALO], US",
  "Diu, [DIU], India",
  "Nyala, [UYL], Sudan",
  "Sirt, [SRX], Libya",
  "Catumbela, [CBT], Angola",
  "Solwesi, [SLI], Zambia",
  "Hemavan, [HMV], Sweden",
  "Torsby, [TYF], Sweden",
  "Karlstad, [KSD], Sweden",
  "Hagfors, [HFS], Sweden",
  "Sandane, [SDN], Norway",
  "Røst, [RET], Norway",
  "Dongloe, [CFN], Ireland",
  "Westray, [WRY], UK",
  "Stronsay, [SOY], UK",
  "Churchill Falls, [ZUM], Canada",
  "Sachigo Lake, [ZPB], Canada",
  "Kashechewan, [ZKE], Canada",
  "Eastmain River, [ZEM], Canada",
  "Salluit, [YZG], Canada",
  "Webequie, [YWP], Canada",
  "Wemindji, [YNC], Canada",
  "Lansdowne House, [YLH], Canada",
  "Akulivik, [AKV], Canada",
  "Ivujivik, [YIK], Canada",
  "Nemiscau, [YNS], Canada",
  "Quaqtaq, [YQC], Canada",
  "Gillam, [YGX], Canada",
  "Fort Albany, [YFA], Canada",
  "Attawapiskat, [YAT], Canada",
  "Kasabonika, [XKS], Canada",
  "Cat Lake, [YAC], Canada",
  "La Tabatière, [ZLT], Canada",
  "Poplar Hill, [YHP], Canada",
  "Kingfisher Lake, [KIF], Canada",
  "Rigolet, [YRG], Canada",
  "Uummannaq, [JQA], Greenland",
  "Maniitsoq, [JSU], Greenland",
  "Paamiut, [JFR], Greenland",
  "Ramata, [RBV], Solomon Islands",
  "Benbecula, [BEB], UK",
  "Wick, [WIC], UK",
  "Hawarden, [CEG], UK",
  "Alderney, [ACI], Guernsey",
  "Dawson Creek, [YDQ], Canada",
  "Savonlinna, [SVL], Finland",
  "Rovaniemi, [RVN], Finland",
  "Dubuque IA, [DBQ], US",
  "Austin TX, [ATT], US",
  "Kittila, [KTT], Finland",
  "Usinsk, [USK], Russia",
  "Joplin, [JLN], US",
  "Cody, [COD], US",
  "Kajaani, [KAJ], Finland",
  "Morgantown, [MGW], US",
  "Saint Cloud, [STC], US",
  "Flagstaff, [FLG], US",
  "Lawton, [LAW], US",
  "Fort Good Hope, [YGH], Canada",
  "Tulita, [ZFN], Canada",
  "Deline, [YWJ], Canada",
  "Kaadedhdhoo, [KDM], Maldives",
  "Bundaberg, [BDB], Australia",
  "Caldas Novas, [CLV], Brazil",
  "Laoag, [LAO], Philippines",
  "Kastelorizo, [KZS], Greece",
  "Paros, [PAS], Greece",
  "Milos, [MLO], Greece",
  "Johnstown, [JST], US",
  "Tartu, [TAY], Estonia",
  "Tuy Hoa, [TBB], Vietnam",
  "Chu Lai, [VCL], Vietnam",
  "Dong Hoi, [VDH], Vietnam",
  "Petersburg, [PSG], US",
  "Nan, [NNT], Thailand",
  "Victoria, [YWH], Canada",
  "Saint George, [SGU], US",
  "Armidale, [ARM], Australia",
  "Franklin, [FKL], US",
  "Hervey Bay, [HVB], Australia",
  "Decatur, [DEC], US",
  "Jacksn Hole, [JAC], US",
  "Redang, [RDN], Malaysia",
  "New Haven, [HVN], US",
  "Kassel, [KSF], Germany",
  "Emerald, [EMD], Australia",
  "Nevsehir, [NAV], Turkey",
  "Socotra, [SCT], Yemen",
  "Pullman, [PUW], US",
  "Khon Kaen, [KKC], Thailand",
  "Nakhon Phanom, [KOP], Thailand",
  "Florence, [FLO], US",
  "Valdez, [VDZ], US",
  "Lahania-kapalua, [JHM], US",
  "Texarkana, [TXK], US",
  "Macon, [MCN], US",
  "Sioux City, [SUX], US",
  "Roswell, [ROW], US",
  "Seattle, [BFI], US",
  "Abilene, [ABI], US",
  "San Angelo, [SJT], US",
  "Jackson, [MKL], US",
  "Waco, [ACT], US",
  "Altoona, [AOO], US",
  "Imperial, [IPL], US",
  "Wichita Falls, [SPS], US",
  "Columbus, [LCK], US",
  "Homer, [HOM], US",
  "Williston, [ISN], US",
  "Beaumont, [BPT], US",
  "Charlo, [YCL], Canada",
  "Williamsport, [IPT], US",
  "International Falls, [INL], US",
  "Presque Isle, [PQI], US",
  "Garden City, [GCK], US",
  "Longview, [GGG], US",
  "Harrison, [HRO], US",
  "Point Lay, [PIZ], US",
  "Barter Island, [BTI], US",
  "Castlegar, [YCG], Canada",
  "Weipa, [WEI], Australia",
  "Ipoh, [IPH], Malaysia",
  "Kerteh, [KTE], Malaysia",
  "Nanaimo, [YCD], Canada",
  "Ketapang, [KTG], Indonesia",
  "Luwuk, [LUW], Indonesia",
  "Thandwe, [SNW], Burma",
  "Myeik, [MGZ], Burma",
  "Trang, [TST], Thailand",
  "Pattaya, [UTP], Thailand",
  "Tirupeti, [TIR], India",
  "Allahabad, [IXD], India",
  "Agra, [AGR], India",
  "Porbandar, [PBD], India",
  "Bhaunagar, [BHU], India",
  "Bhuj, [BHJ], India",
  "Antwerp, [ANR], Belgium",
  "Magnetiogorsk, [MQF], Russia",
  "Gabes, [GAE], Tunisia",
  "Ponce, [PSE], Puerto Rico",
  "Valera, [VLV], Venezuela",
  "Merida, [MRD], Venezuela",
  "Barinas, [BNS], Venezuela",
  "Piura, [PIU], Peru",
  "Tacna, [TCQ], Peru",
  "Ayacucho, [AYP], Peru",
  "Potosi, [POI], Bolivia",
  "Valledupar, [VUP], Colombia",
  "Arauca, [AUC], Colombia",
  "Tame, [TME], Colombia",
  "Neiva, [NVA], Colombia",
  "Guapi, [GPI], Colombia",
  "Florencia, [FLA], Colombia",
  "Corozal, [CZU], Colombia",
  "Buenaventura, [BUN], Colombia",
  "Armenia, [AXM], Colombia",
  "Galapagos, [GPS], Ecuador",
  "Valdivia, [ZAL], Chile",
  "Easter Island, [IPC], Chile",
  "Calabar, [CBQ], Nigeria",
  "Benin, [BNI], Nigeria",
  "Rio Grande, [RIG], Brazil",
  "Santo Angelo, [GEL], Brazil",
  "Campina Grande, [CPV], Brazil",
  "Criciuma, [CCM], Brazil",
  "Aracatuba, [ARU], Brazil",
  "Takoradi, [TKD], Ghana",
  "Rio Grande, [RGA], Argentina",
  "Jujuy, [JUJ], Argentina",
  "San Julian, [UAQ], Argentina",
  "Tucuman, [TUC], Argentina",
  "San Rafael, [AFA], Argentina",
  "Santa Fe, [SFN], Argentina",
  "Zarzaitine, [IAM], Algeria",
  "Parana, [PRA], Argentina",
  "Pagadian, [PAG], Philippines",
  "El Golea, [ELG], Algeria",
  "Misawa, [MSJ], Japan",
  "Tokushima, [TKS], Japan",
  "Amami, [ASJ], Japan",
  "Iki, [IKI], Japan",
  "Wakkanai, [WKJ], Japan",
  "Nakashibetsu, [SHB], Japan",
  "Matsumoto, [MMJ], Japan",
  "Yap, [YAP], Micronesia",
  "Kosrae, [KSA], Micronesia",
  "Chuuk, [TKK], Micronesia",
  "Tilrempt, [HRM], Algeria",
  "Zhob, [PZH], Pakistan",
  "Moenjodaro, [MJD], Pakistan",
  "Faisalabad, [LYP], Pakistan",
  "Aqaba, [AQJ], Jordan",
  "Ramsar, [RZR], Iran",
  "Birjand, [XBJ], Iran",
  "Bandar Lengeh, [BDH], Iran",
  "Bandar Mahshahr, [MRX], Iran",
  "Sharurah, [SHW], Saudi Arabia",
  "Arar, [RAE], Saudi Arabia",
  "Guriat, [URY], Saudi Arabia",
  "Whangarei, [WRE], New Zealand",
  "Gisborne, [GIS], New Zealand",
  "Taupo, [TUO], New Zealand",
  "Ouvea, [UVE], New Caledonia",
  "Port Hardy, [YZT], Canada",
  "Koumac, [KOC], New Caledonia",
  "Mayaguana, [MYG], Bahamas",
  "Stella Maris, [SML], Bahamas",
  "Dead Man's Cay, [LGI], Bahamas",
  "Matthew Town, [IGA], Bahamas",
  "Rock Sound, [RSD], Bahamas",
  "Alice Town, [BIM], Bahamas",
  "Treasure Cay, [TCB], Bahamas",
  "Spring Point, [AXP], Bahamas",
  "David, [DAV], Panama",
  "Tapachula, [TAP], Mexico",
  "Uruapan, [UPN], Mexico",
  "Piedras Negras, [PDS], Mexico",
  "Minatitlan, [MTT], Mexico",
  "Matamoros, [MAM], Mexico",
  "Lazard Cardenas, [LZC], Mexico",
  "Saltillo, [SLW], Mexico",
  "Ciudad Victoria, [CVM], Mexico",
  "Campeche, [CPE], Mexico",
  "North Bay, [YYB], Canada",
  "Abbotsford, [YXX], Canada",
  "Denizli, [DNZ], Turkey",
  "Merzifon, [MZH], Turkey",
  "Altenrhein, [ACH], Switzerland",
  "Lugano, [LUG], Switzerland",
  "Satu Mare, [SUJ], Romania",
  "Oradea, [OMR], Romania",
  "Craiova, [CRA], Romania",
  "Baia Mare, [BAY], Romania",
  "Haifa, [HFA], Israel",
  "Bolzano, [BZO], Italy",
  "Debrecen, [DEB], Hungary",
  "Skiathos, [JSI], Greece",
  "Ioannina, [IOA], Greece",
  "Lorient, [LRT], France",
  "Deauville, [DOL], France",
  "Sachs Harbour, [YSY], Canada",
  "Chalons, [XCR], France",
  "Avignon, [AVN], France",
  "Resolute, [YRB], Canada",
  "Perigueux, [PGX], France",
  "Agen, [AGF], France",
  "Sydney, [YQY], Canada",
  "Badajoz, [BJZ], Spain",
  "Plovdiv, [PDV], Bulgaria",
  "El Fasher, [ELF], Sudan",
  "Gondar, [GDQ], Ethiopia",
  "Axum, [AXU], Ethiopia",
  "Fort Chipewyan, [YPY], Canada",
  "Prince Pupert, [YPR], Canada",
  "Ouarzazate, [OZZ], Morocco",
  "Monrovia, [MLW], Liberia",
  "Port Menier, [YPN], Canada",
  "Kindu, [KND], Congo (Kinshasa)",
  "Bunia, [BUX], Congo (Kinshasa)",
  "Thule, [THU], Greenland",
  "Oriximina, [ORX], Brazil",
  "Patos de Minas, [POJ], Brazil",
  "Crooked Creek, [CKD], US",
  "Coffman Cove, [KCC], US",
  "Scammon Bay, [SCM], US",
  "Port Lions, [ORI], US",
  "Old Harbor, [OLH], US",
  "Weyers Cave, [SHD], US",
  "Bella Coola, [QBC], Canada",
  "Coen, [CUQ], Australia",
  "Tufi, [TFI], Papua New Guinea",
  "Waala, [BMY], New Caledonia",
  "Beckley, [BKW], US",
  "Eday, [EOI], UK",
  "Bathurst, [ZBF], Canada",
  "Deer Lake, [YVZ], Canada",
  "Ivalo, [IVL], Finland",
  "Blackall, [BKQ], Australia",
  "Al Ghaidah Intl, [AAY], Yemen",
  "Saidpur, [SPD], Bangladesh",
  "Gafsa, [GAF], Tunisia",
  "San Luis, [LUQ], Argentina",
  "Ghriss, [MUW], Algeria",
  "Tiaret, [TID], Algeria",
  "Djanet, [DJG], Algeria",
  "Kapuskasing, [YYU], Canada",
  "Pamplona, [PNA], Spain",
  "Lodwar, [LOK], Kenya",
  "Asosa, [ASO], Ethiopia",
  "Jimma, [JIM], Ethiopia",
  "Gambella, [GMB], Ethiopia",
  "Bahar Dar, [BJR], Ethiopia",
  "Arba Minch, [AMH], Ethiopia",
  "Ziguinchor, [ZIG], Senegal",
  "Praslin, [PRI], Seychelles",
  "Port Gentil, [POG], Gabon",
  "Luena, [LUO], Angola",
  "M'banza-congo, [SSY], Angola",
  "Kastamonu, [KFS], Turkey",
  "Mananara, [WMR], Madagascar",
  "Mamuju, [MJU], Indonesia",
  "Thanh Hoa, [THD], Vietnam",
  "Mfuwe, [MFU], Zambia",
  "Kutahya, [KZR], Turkey",
  "N'gaoundere, [NGE], Cameroon",
  "Maroua, [MVR], Cameroon",
  "Dalma Island, [ZDY], UAE",
  "Veliky Ustyug, [VUS], Russia",
  "Kangding, [KGT], China",
  "Rio Hondo, [RHD], Argentina",
  "Manzini, [MTS], Swaziland",
  "Yuzhno-Kurilsk, [DEE], Russia",
  "Qabala, [GBB], Azerbaijan",
  "Gorno-Altaysk, [RGK], Russia",
  "Pomalaa, [PUM], Indonesia",
  "Umtata, [UTT], South Africa",
  "Lloydminster, [YLL], Canada",
  "Lephalale, [ELL], South Africa",
  "Polokwane, [PTG], South Africa",
  "Keewaywin, [KEW], Canada",
  "Margate, [MGH], South Africa",
  "Eirunepe, [ERN], Brazil",
  "Bointo, [BYO], Brazil",
  "Redencao, [RDC], Brazil",
  "Trail, [YZZ], Canada",
  "Vinnitsa, [VIN], Ukraine",
  "Mulatupo, [MPP], Panama",
  "Garachine, [GHE], Panama",
  "Achutupo, [ACU], Panama",
  "Goodnews Bay, [GNU], US",
  "Puerto Obaldia, [PUE], Panama",
  "El Porvenir, [PVE], Panama",
  "Playon Chico, [PYC], Panama",
  "Marktoberdorf, [OAL], Germany",
  "Mysore, [MYQ], India",
  "Stephenville, [YJT], Canada",
  "Los Alamos, [LAM], US",
  "Dickwella, [DIW], Sri Lanka",
  "Ulaangom, [ULO], Mongolia",
  "Yasuj, [YES], Iran",
  "Longyan, [LCX], China",
  "Iturup Island, [BVV], Russia",
  "Olgii, [ULG], Mongolia",
  "Lleida, [ILD], Spain",
  "Pakuba, [PAF], Uganda",
  "Guanambi, [GNM], Brazil",
  "Barcelos, [BAZ], Brazil",
  "Coari, [CIZ], Brazil",
  "Araxa, [AAX], Brazil",
  "Rio Verde, [RVD], Brazil",
  "Guarapuava, [GPB], Brazil",
  "Rondonopolis, [ROO], Brazil",
  "Minacu, [MQH], Brazil",
  "Parintins, [PIN], Brazil",
  "Gurupi, [GRP], Brazil",
  "Villa Garzon, [VGZ], Colombia",
  "La Macarena, [LMC], Colombia",
  "Uyuni, [UYU], Bolivia",
  "Manley Hot Springs, [MLY], US",
  "Kake, [KAE], US",
  "Healy, [HKB], US",
  "Stony River, [SRV], US",
  "Red Devil, [RDV], US",
  "Circle, [IRC], US",
  "Ornskoldsvik, [OER], Sweden",
  "Takotna, [TCT], US",
  "Nikolai, [NIB], US",
  "Nelson Lagoon, [NLG], US",
  "False Pass, [KFP], US",
  "Nikolski, [IKO], US",
  "Atka, [AKB], US",
  "Tin City, [TNC], US",
  "Seal Bay, [SYB], US",
  "Kitoi Bay, [KKB], US",
  "Amook Bay, [AOS], US",
  "Larsen Bay, [KLN], US",
  "Akhiok, [AKK], US",
  "South Naknek, [WSN], US",
  "Pilot Point, [PIP], US",
  "Perryville, [KPV], US",
  "Chignik Lagoon, [KCL], US",
  "Egegik, [EGX], US",
  "Chignik Lake, [KCQ], US",
  "North Whale Pass, [WWP], US",
  "Port Protection, [PPV], US",
  "Point Baker, [KPB], US",
  "Hydaburg, [HYG], US",
  "Excursion Inlet, [EXI], US",
  "Pelican, [PEC], US",
  "Tenakee Springs, [TKE], US",
  "Elfin Cove, [ELV], US",
  "Angoon, [AGN], US",
  "Merced, [MCE], US",
  "Visalia, [VIS], US",
  "Coldfoot, [CXF], US",
  "Brich Creek, [KBC], US",
  "Central, [CEM], US",
  "Rampart, [RMP], US",
  "Minto, [MNT], US",
  "Levelock, [KLL], US",
  "Chuathbaluk, [CHU], US",
  "Eastsound, [ESD], US",
  "Friday Harbor, [FRD], US",
  "Vernal, [VEL], US",
  "Moab, [CNY], US",
  "Wolf Point, [OLF], US",
  "Glendive, [GDV], US",
  "McCook, [MCK], US",
  "Sidney, [SDY], US",
  "Manistee, [MBL], US",
  "Gunnison, [GUC], US",
  "Gelendzik, [GDZ], Russia",
  "Kristianstad, [KID], Sweden",
  "Thief River Falls, [TVF], US",
  "Yaroslavl, [IAR], Russia",
  "Trollhattan, [THN], Sweden",
  "Wenatchee, [EAT], US",
  "Pendleton, [PDT], US",
  "Riverton WY, [RIW], US",
  "Montrose CO, [MTJ], US",
  "Marion, [MWA], US",
  "Escanaba, [ESC], US",
  "Orange, [OAG], Australia",
  "Grafton, [GFN], Australia",
  "Hamadan, [HDM], Iran",
  "Çorlu, [TEQ], Turkey",
  "Sinop, [SIC], Turkey",
  "Canakkale, [CKZ], Turkey",
  "Eskissehir, [AOE], Turkey",
  "Walaha, [WLH], Vanuatu",
  "Tanjung Manis, [TGC], Malaysia",
  "Togiak Village, [TOG], US",
  "Port Heiden, [PTH], US",
  "King Cove, [KVC], US",
  "Igiugig, [IGG], US",
  "Burgos, [RGS], Spain",
  "Leon, [LEN], Spain",
  "Lago Agrio, [LGQ], Ecuador",
  "Parsabad, [PFQ], Iran",
  "Ilam, [IIL], Iran",
  "Apatity, [KVK], Russia",
  "Cauayan, [CYZ], Philippines",
  "Arctic Village, [ARC], US",
  "Mekoryuk, [MYU], US",
  "Skien, [SKE], Norway",
  "Roros, [RRS], Norway",
  "Orland, [OLA], Norway",
  "Tambow, [TBW], Russia",
  "Provincetown, [PVC], US",
  "Boulder City, [BLD], US",
  "Grand Canyon West, [GCW], US",
  "Fagernes, [VDB], Norway",
  "Bardufoss, [BDU], Norway",
  "Khovd, [HVD], Mongolia",
  "Altai, [LTI], Mongolia",
  "Whyalla, [WYA], Australia",
  "Thargomindah, [XTG], Australia",
  "Argyle, [PUG], Australia",
  "Olympic Dam, [OLP], Australia",
  "Moree, [MRZ], Australia",
  "Milingimbi, [MGT], Australia",
  "Lismore, [LSY], Australia",
  "Horn Island, [HID], Australia",
  "Elcho Island, [ELC], Australia",
  "Devonport, [DPO], Australia",
  "Ceduna, [CED], Australia",
  "Coober Pedy, [CPD], Australia",
  "Barcaldine, [BCI], Australia",
  "Bakalalan, [BKM], Malaysia",
  "Kawthoung, [KAW], Burma",
  "Dienbienphu, [DIN], Vietnam",
  "Soenderborg, [SGD], Denmark",
  "Tak, [MAQ], Thailand",
  "Nepalgunj, [KEP], Nepal",
  "Chandragarhi, [BDP], Nepal",
  "Ronne, [RNN], Denmark",
  "Bharatpur, [BHR], Nepal",
  "Barisal, [BZL], Bangladesh",
  "Shillong, [SHL], India",
  "Penza, [PEZ], Russia",
  "Orsk, [OSW], Russia",
  "Kursk, [URS], Russia",
  "Lopez, [LPS], US",
  "Silver City, [SVC], US",
  "Akutan, [KQA], US",
  "Greenville, [GLH], US",
  "Kearney, [EAR], US",
  "Elista, [ESL], Russia",
  "Beslan, [OGZ], Russia",
  "Grozny, [GRV], Russia",
  "Igarka, [IAA], Russia",
  "Karup, [KRP], Denmark",
  "Kyzyl, [KYZ], Russia",
  "Petrozavodsk, [PES], Russia",
  "Uzhgorod, [UDJ], Ukraine",
  "Kingston, [YGK], Canada",
  "Nakhchivan, [NAJ], Azerbaijan",
  "Santa Rosa, [SRA], Brazil",
  "Riberalta, [RIB], Bolivia",
  "Guayaramerín, [GYA], Bolivia",
  "Nuquí, [NQU], Colombia",
  "La Pedrera, [LPD], Colombia",
  "Lençóis, [LEC], Brazil",
  "Masbate, [MBT], Philippines",
  "Virac, [VRC], Philippines",
  "Jolo, [JOL], Philippines",
  "Camiguin, [CGM], Philippines",
  "Wonju, [WJU], South Korea",
  "Shonai, [SYO], Japan",
  "Odate Noshiro, [ONJ], Japan",
  "Iwami, [IWJ], Japan",
  "Adak Island, [ADK], US",
  "Boca de Sábalo, [SAX], Panama",
  "Bahia Piña, [BFQ], Panama",
  "Skardu, [KDU], Pakistan",
  "Dalbandin, [DBA], Pakistan",
  "Sabzevar, [AFZ], Iran",
  "Bojnourd, [BJB], Iran",
  "Bam, [BXR], Iran",
  "Khorram Abad, [KHD], Iran",
  "Anelghowhat, [AUY], Vanuatu",
  "Valesdir, [VLS], Vanuatu",
  "Tongoa Island, [TGH], Vanuatu",
  "Maewo Island, [MWF], Vanuatu",
  "Sangafa, [EAE], Vanuatu",
  "Vanua Balavu, [VBV], Fiji",
  "Rotuma, [RTA], Fiji",
  "Lakeba Island, [LKB], Fiji",
  "Cicia, [ICI], Fiji",
  "Long Banga, [LBP], Malaysia",
  "San Jose, [SYQ], Costa Rica",
  "Roxana, [TTQ], Costa Rica",
  "Jaqué, [JQE], Panama",
  "Ubari, [QUB], Libya",
  "Isparta, [ISE], Turkey",
  "Yakima, [YKM], US",
  "Victoria, [VCT], US",
  "Quincy, [UIN], US",
  "Salina, [SLN], US",
  "Saranac Lake, [SLK], US",
  "Sheridan, [SHR], US",
  "Rutland, [RUT], US",
  "Portsmouth, [PSM], US",
  "Pellston, [PLN], US",
  "Pocatello, [PIH], US",
  "Hattiesburg/Laurel, [PIB], US",
  "Muscle Shoals, [MSL], US",
  "Muskegon, [MKG], US",
  "Lancaster, [LNS], US",
  "North Platte, [LBF], US",
  "Laramie, [LAR], US",
  "Kirksville, [IRK], US",
  "Glasgow, [GGW], US",
  "Elko, [EKO], US",
  "Eau Claire, [EAU], US",
  "Hancock, [CMX], US",
  "Port Angeles, [CLM], US",
  "Sault Ste Marie, [CIU], US",
  "Cape Girardeau, [CGI], US",
  "Scottsbluff, [BFF], US",
  "Walla Walla, [ALW], US",
  "Athens, [AHN], US",
  "Aberdeen, [ABR], US",
  "Arua, [RUA], Uganda",
  "Bukoba, [BKZ], Tanzania",
  "Lokichoggio, [LKG], Kenya",
  "Gode, [GDE], Ethiopia",
  "Sao Filipe, [SFL], Fogo Island",
  "La Gomera, [GMZ], Spain",
  "Oranjemund, [OMD], Namibia",
  "Ondangwa, [OND], Namibia",
  "Luderitz, [LUD], Namibia",
  "Chimoio, [VPY], Mozambique",
  "Mocamedes, [MSZ], Angola",
  "Chipata, [CIP], Zambia",
  "Barra, [BRR], UK",
  "Land's End, [LEQ], UK",
  "Campbeltown, [CAL], UK",
  "Guemar, [ELU], Algeria",
  "Béchar, [CBH], Algeria",
  "Masset, [ZMT], Canada",
  "Gamètì, [YRA], Canada",
  "Powell River, [YPW], Canada",
  "Peawanuck, [YPO], Canada",
  "Lutselk'e, [YSG], Canada",
  "Kimmirut, [YLC], Canada",
  "Grise Fiord, [YGZ], Canada",
  "Tarapacá, [TCD], Colombia",
  "Ogoki Post, [YOG], Canada",
  "Summer Beaver, [SUR], Canada",
  "Whatì, [YLE], Canada",
  "Anahim Lake, [YAA], Canada",
  "Mendi, [MDU], Papua New Guinea",
  "Tiree, [TRE], UK",
  "Marau, [RUS], Solomon Islands",
  "Atoifi, [ATD], Solomon Islands",
  "Dundee, [DND], UK",
  "Islay, [ILY], UK",
  "Golouchestershire, [GLO], UK",
  "Kuopio, [KUO], Finland",
  "Kogalym, [KGP], Russia",
  "Kuusamo, [KAO], Finland",
  "Narvik, [NVK], Norway",
  "Hayden, [HDN], US",
  "Cortez, [CEZ], US",
  "Meridian, [MEI], US",
  "Georgetown, [OGL], Guyana",
  "Chumphon, [CJM], Thailand",
  "Joensuu, [JOE], Finland",
  "Bemidji, [BJI], US",
  "Monaco, [MCM], Monaco",
  "Twin Falls, [TWF], US",
  "Vail, [EGE], US",
  "Paulatuk, [YPC], Canada",
  "Grand Canyon, [GCN], US",
  "Dhangarhi, [DHI], Nepal",
  "Tumling Tar, [TMI], Nepal",
  "Brac, [BWK], Croatia",
  "Pai, [PYY], Thailand",
  "Ca Mau, [CAH], Vietnam",
  "Rach Gia, [VKG], Vietnam",
  "Muang Xay, [ODY], Laos",
  "Luang Namtha, [LXG], Laos",
  "Trat, [TDX], Thailand",
  "Ranong, [UNN], Thailand",
  "Buri Ram, [BFV], Thailand",
  "Roi Et, [ROI], Thailand",
  "Kuressaare, [URE], Estonia",
  "PADUCAH, [PAH], US",
  "PARKERSBURG, [PKB], US",
  "Vancouver, [CXH], Canada",
  "Redding, [RDD], US",
  "Sihanoukville, [KOS], Cambodia",
  "Carlsbad, [CLD], US",
  "Mae Hong Son, [HGN], Thailand",
  "Phon Savan, [XKH], Laos",
  "Funafuti, [FUN], Tuvalu",
  "Kingscote, [KGC], Australia",
  "Rockland, [RKD], US",
  "Bar Harbor, [BHB], US",
  "Butte, [BTM], US",
  "Naples, [APF], US",
  "Ataq, [AXK], Yemen",
  "Gyumri, [LWN], Armenia",
  "Sukhothai, [THS], Thailand",
  "Waingapu, [WGP], Indonesia",
  "Naha, [NAH], Indonesia",
  "Topeka, [FOE], US",
  "Cedar City, [CDC], US",
  "Modesto, [MOD], US",
  "Stockton, [SCK], US",
  "Belleville, [BLV], US",
  "Hobbs, [HOB], US",
  "Augsburg, [AGB], Germany",
  "Ogdensburg, [OGS], US",
  "Chico, [CIC], US",
  "Augusta, [AUG], US",
  "Fort Leonardwood, [TBN], US",
  "Hibbing, [HIB], US",
  "Teterboro, [TEB], US",
  "Hamburg, [XFW], Germany",
  "San Luis, [SPB], US",
  "Havre, [HVR], US",
  "Carlsbad, [CNM], US",
  "Jonesboro, [JBR], US",
  "Mannheim, [MHG], Germany",
  "Massena, [MSS], US",
  "Kamuela, [MUE], US",
  "Pueblo, [PUB], US",
  "Prescott, [PRC], US",
  "Hana, [HNM], US",
  "Port Moller, [PTU], US",
  "Iliamna, [ILI], US",
  "Tatalina, [TLJ], US",
  "Cape Lisburne, [LUR], US",
  "Wajima, [NTQ], Japan",
  "Tamworth, [TMW], Australia",
  "Richmond, [RCM], Australia",
  "Melbourne, [MEB], Australia",
  "Avalon, [AVV], Australia",
  "Amberley, [ABM], Australia",
  "Lahad Datu, [LDU], Malaysia",
  "Limbang, [LMN], Malaysia",
  "Babo, [BXB], Indonesia",
  "Poso, [PSJ], Indonesia",
  "Wamena, [WMX], Indonesia",
  "Putao, [PBU], Burma",
  "Kyaukpyu, [KYP], Burma",
  "Kengtung, [KET], Burma",
  "Loei, [LOE], Thailand",
  "Sakon Nakhon, [SNO], Thailand",
  "Narathiwat, [NAW], Thailand",
  "Phrae, [PRH], Thailand",
  "Lampang, [LPT], Thailand",
  "Agatti Island, [AGX], India",
  "Biratnagar, [BIR], Nepal",
  "Pokhara, [PKR], Nepal",
  "Bhairawa, [BWA], Nepal",
  "Ludhiaha, [LUH], India",
  "Kanpur, [KNU], India",
  "Ostend, [OST], Belgium",
  "Brandon, [YBR], Canada",
  "Gwalior, [GWL], India",
  "Kulu, [KUU], India",
  "Rajshahi, [RJH], Bangladesh",
  "Trinciomalee, [TRR], Sri Lanka",
  "Khajuraho, [HJR], India",
  "Jamnagar, [JGA], India",
  "Belgaum, [IXG], India",
  "Pevek, [PWE], Russia",
  "Mayaguez, [MAZ], Puerto Rico",
  "San Tome, [SOM], Venezuela",
  "San Antonio, [SVZ], Venezuela",
  "La Fria, [LFR], Venezuela",
  "Cumana, [CUM], Venezuela",
  "Coro, [CZE], Venezuela",
  "Canaima, [CAJ], Venezuela",
  "Trujillo, [TRU], Peru",
  "Tumbes, [TBP], Peru",
  "Anta, [ATA], Peru",
  "Andahuaylas, [ANS], Peru",
  "Chiclayo, [CIX], Peru",
  "Yola, [YOL], Nigeria",
  "Sokoto, [SKO], Nigeria",
  "Rio Hacha, [RCH], Colombia",
  "Providencia, [PVA], Colombia",
  "Popayan, [PPN], Colombia",
  "Manizales, [MZL], Colombia",
  "Ipiales, [IPI], Colombia",
  "Tumaco, [TCO], Colombia",
  "Bahia Solano, [BSC], Colombia",
  "Kaduna, [KAD], Nigeria",
  "Manta, [MEC], Ecuador",
  "Macas, [XMS], Ecuador",
  "Jos, [JOS], Nigeria",
  "Ilorin, [ILR], Nigeria",
  "Ibadan, [IBA], Nigeria",
  "Osorno, [ZOS], Chile",
  "Vilhena, [BVH], Brazil",
  "Uruguaiana, [URG], Brazil",
  "Paulo Alfonso, [PAV], Brazil",
  "Tucurui, [TUR], Brazil",
  "Tabatinga, [TBT], Brazil",
  "Oriximina, [TMT], Brazil",
  "Cruzeiro do Sul, [CZS], Brazil",
  "Corumba, [CMG], Brazil",
  "Alta Floresta, [AFL], Brazil",
  "Araracuara, [AQA], Brazil",
  "Santa Rosa, [RSA], Argentina",
  "Sunyani, [NYI], Ghana",
  "Viedma, [VDM], Argentina",
  "Posadas, [PSS], Argentina",
  "Formosa, [FMA], Argentina",
  "Resistencia, [RES], Argentina",
  "La Rioja, [IRJ], Argentina",
  "Catamarca, [CTC], Argentina",
  "San Jose, [SJI], Philippines",
  "Touggourt, [TGR], Algeria",
  "Kumejima, [UEO], Japan",
  "Oshima, [OIM], Japan",
  "Hachijojima, [HAC], Japan",
  "Tottori, [TTJ], Japan",
  "Izumo, [IZO], Japan",
  "Monbetsu, [MBE], Japan",
  "Nanki-shirahama, [SHM], Japan",
  "Tainan, [TNN], Taiwan",
  "Fengnin, [TTT], Taiwan",
  "Tebessa, [TEE], Algeria",
  "Panjgur, [PJG], Pakistan",
  "Gilgit, [GIL], Pakistan",
  "Khasab, [KHS], Oman",
  "Fujeirah, [FJR], UAE",
  "Sanandaj, [SDG], Iran",
  "Wejh, [EJH], Saudi Arabia",
  "Turaif, [TUI], Saudi Arabia",
  "Rafha, [RAH], Saudi Arabia",
  "Fort Mcpherson, [ZFM], Canada",
  "Wanganui, [WAG], New Zealand",
  "Westport, [WSZ], New Zealand",
  "Whakatane, [WHK], New Zealand",
  "Timaru, [TIU], New Zealand",
  "Kaitaia, [KAT], New Zealand",
  "Kerikeri, [KKE], New Zealand",
  "Hokitika, [HKK], New Zealand",
  "Touho, [TOU], New Caledonia",
  "Mare, [MEE], New Caledonia",
  "Kone, [KNQ], New Caledonia",
  "Sarnia, [YZR], Canada",
  "Sandspit, [YZP], Canada",
  "Guantanamo, [GAO], Cuba",
  "Changuinola, [CHX], Panama",
  "Nuevo Laredo, [NLD], Mexico",
  "Loreto, [LTO], Mexico",
  "Penticton, [YYF], Canada",
  "Chetumal, [CTM], Mexico",
  "Guanaja, [GJA], Honduras",
  "Medicine Hat, [YXH], Canada",
  "Constanta, [CND], Romania",
  "Arad, [ARW], Romania",
  "Brno, [BRQ], Czech Republic",
  "Isafjordur, [IFJ], Iceland",
  "Kastoria, [KSO], Greece",
  "Tuktoyaktuk, [YUB], Canada",
  "Dijon, [DIJ], France",
  "Quimper, [UIP], France",
  "Lannion, [LAI], France",
  "Le Havre, [LEH], France",
  "Aurillac, [AUR], France",
  "Le Puy, [LPY], France",
  "Angouleme, [ANG], France",
  "Salamanca, [SLM], Spain",
  "Egilsstadir, [EGS], Iceland",
  "Mtwara, [MYW], Tanzania",
  "Arusha, [ARK], Tanzania",
  "Kamembe, [KME], Rwanda",
  "Ghadames, [LTD], Libya",
  "Lethbridge, [YQL], Canada",
  "Ghat, [GHT], Libya",
  "Kitale, [KTL], Kenya",
  "Abu Simbel, [ABS], Egypt",
  "Maio, [MMO], Cape Verde",
  "Akureyri, [AEY], Iceland",
  "Cap Skiring, [CSK], Senegal",
  "Tetouan, [TTU], Morocco",
  "Al Hociema, [AHU], Morocco",
  "Tan Tan, [TTA], Morocco",
  "Pickle Lake, [YPL], Canada",
  "Isiro, [IRP], Congo (Kinshasa)",
  "Maseru, [MSU], Lesotho",
  "Santa Terezinha, [STZ], Brazil",
  "Breves, [BVS], Brazil",
  "Zachar Bay, [KZB], US",
  "Port Williams, [KPR], US",
  "Karluk, [KYK], US",
  "Dalanzadgad, [DLZ], Mongolia",
  "Portland, [PTJ], Australia",
  "Alofi, [IUE], Niue",
  "Lodja, [LJA], Congo (Kinshasa)",
  "Utila, [UII], Honduras",
  "Massawa, [MSW], Eritrea",
  "Tulcan, [TUA], Ecuador",
  "Ovda, [VDA], Israel",
  "Kozani, [KZI], Greece"
  ];

export default airports;
